### ISSUE TITLE
Ruby version 2.1.6 throws SyntaxError from lib/administrate/field/has_one.rb:21

### ISSUE THREAD

**Issue by Pcushing** [thoughtbot/administrate#1010]
I was just installing administrate on a brand new app and my first launch of the dashboard threw this:

```
SyntaxError in Admin::UsersController#index
/Users/patrickcushing/.rvm/gems/ruby-2.1.6/gems/administrate-0.8.1/lib/administrate/field/has_one.rb:21: syntax error, unexpected ':', expecting => { "#{attr}_attributes": related_dashboard_attributes } ^ /Users/patrickcushing/.rvm/gems/ruby-2.1.6/gems/administrate-0.8.1/lib/administrate/field/has_one.rb:27: syntax error, unexpected end-of-input, expecting keyword_end
```

Here's the line in question: https://github.com/thoughtbot/administrate/blob/master/lib/administrate/field/has_one.rb#L21

Swiching over to ruby 2.2.2 seemed to resolve the issue. I don't see anything specific to ruby versions in the README so I figured I'd report. A simple mention there would be helpful. I'm not in the position to propose a more robust fix this moment, but can take a look next week if desired.

**Comment by nickcharlton** [comment]
Hi @Pcushing!

Thanks for reporting this. We state that we support Rails 4.1 and above, [so that should mean we support Ruby 2.2.2](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions).

But, we'd not been testing Ruby versions as CircleCI didn't support a form of build matrices. It can do this now with [Circle CI 2.0](https://circleci.com/docs/2.0/workflows/).

If you'd be willing to take a look at a solution to this with Ruby 2.1.6 that'd be great! In the meantime, I'm going to look into testing against different Ruby versions.
