### ISSUE TITLE
HasMany Show should render relationship collection partial

### ISSUE THREAD

**Issue by GeekOnCoffee** [thoughtbot/administrate#1191]
Currently: A HasMany field renders the collection partial for the dashboard being viewed
Desired: A HasMany field should render the collection partial for the relationship being rendered. 

https://github.com/thoughtbot/administrate/blob/master/app/views/fields/has_many/_show.html.erb#L25

**Comment by ctrombley** [comment]
+1 

I would be happy to take a stab at a PR if the maintainers are interested.

**Comment by 8vius** [comment]
+1 

Ran into this today and it's quite confusing.

**Comment by stratigos** [comment]
This appears related to (if not the same issue as) #1183

**Comment by stratigos** [comment]
Im running into an issue that I believe is related to this (so I dont want to open a new issue for it). When I have pagination on my nested `HasMany` association, I get an unpermitted parameters error on the association name. It is defined in the parent's `SHOW_PAGE_ATTRIBUTES`. However, since the view-template for the association is using the same `collection` view, it tries to use its parent's `COLLECTION_ATTRIBUTES`, and then fails because I dont have (and dont want) the association attribute on the collection/index page. 

I think the strong/permitted parameters in the nested `HasMany` association list, when viewing a parent's `#show` page, should be derived from `SHOW_PAGE_ATTRIBUTES` instead. Given the architecture for how views are loaded, Im not sure where to begin for a fix.

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a long time since the last activity; but if this is still an issue please open a new issue.
