### ISSUE TITLE
How to make boolean field to be checkbox on the index page?

### ISSUE THREAD

**Issue by arkdy** [thoughtbot/administrate#1209]
Hi there,

I'd like to know whether it's possible to make boolean field behave as a checkbox on listing (index) page? 
The idea is very simple, save time when you want to mark checked/uncheked inplace (ajax). Currently to do such a simple thing, you should go to Edit page and click on checkbox.

Any suggestions how to implement it are very appreciated. Thanks in advance!

**Comment by hopewise** [comment]
Did you solve this?

**Comment by arkdy** [comment]
Unfortunately, no. I switched to rails_admin because of it's extended functionality.

**Comment by LukeDurrant** [comment]
In the `ATTRIBUTE_TYPES` change the field to Field::Boolean

**Comment by nickcharlton** [comment]
Currently, we just render the string representation of the field. So, if it's not set at all, you'll get `-`. Otherwise `true`/`false` respectively.

As there's no interactivity there, it's currently not possible. I'd love to see it though and would definitely welcome a PR adding that!

In the mean time I'm gong to close this issue.
