### ISSUE TITLE
Total number of records in table

### ISSUE THREAD

**Issue by DhanashreeDorage** [thoughtbot/administrate#1309]
I am trying to get total number of records in a table, in front of table name. Can you please help me with modifying administrate view specifically the Table name?

**Comment by kostadriano** [comment]
You can use the administrate generators, like this: 
`rails generate administrate:views:index YourModelName`

Instead of `index` you can change to `show/edit` or the page that you want to customize.

This will create an `html.erb` file with all the information that your administrate page used to have, there you can customize as you want, without doing any effect in other pages.

In [this link](https://administrate-prototype.herokuapp.com/customizing_page_views) on `Customizing for a specific resource` section you can find more examples. :smile:

**Comment by DhanashreeDorage** [comment]
I followed this document but I am not able add code after table name. 
I want total count as Users(90).

**Comment by purinkle** [comment]
@DhanashreeDorage, are you still having issues customising your views?

**Comment by DhanashreeDorage** [comment]
Hello,

I am still having problem to update the views.

**Comment by robinvdijk** [comment]
@DhanashreeDorage If I understand what you're trying to do then the easiest solution would be to do the following:

First generate the sidebar file using `rails generate administrate:views:navigation`.

Within that file there is a `link_to` helper. You can edit it so it contains something like 
`"#{display_resource_name(resource)} (#{class_from_resource(resource).count})"`

**Comment by nickcharlton** [comment]
I'm going to close this as @robinvdijk provides a good solution here. Please open a new issue if this isn't the case!

**Comment by DhanashreeDorage** [comment]
Thanks Robin. It worked
