### ISSUE TITLE
Administrate trying to admin my sessions

### ISSUE THREAD

**Issue by donatoaz** [thoughtbot/administrate#1333]
I have a custom sessions controller on my admin namespace and it seems to be causing problems getting Administrate to work.

My intention is to have an Administrate based content management backend and an API namespace that interacts via json.

These are my routes:

```ruby
Rails.application.routes.draw do
  devise_for :users, skip: :all

  namespace :admin do
    resources :administrators
    resources :clients
    resources :inspectors
    
    devise_scope :user do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      delete "/logout", to: "sessions#destroy"
    end

    root to: "inspectors#index"
  end

  namespace :api do
    devise_scope :user do
      post "/login", to: "sessions#create"
      delete "/logout", to: "sessions#destroy"
    end
  end

  root to: "home#index"
end
```

It seems that [this method](https://github.com/thoughtbot/administrate/blob/b3f006b742bfb0186ccecb98fc8c92d7d9a23869/lib/administrate/namespace.rb#L7) is trying to instantiate a Session class based on the fact that my admin namespace has a sessions prefixed route.

How can I work around this? Am I approaching using this gem incorrectly?

Thanks!

**Comment by joshmcarthur** [comment]
@donatoaz this might be too late to be helpful, but I had the same issue, and got around it by extending `Administrate::Namespace#all_routes`:

``` ruby
module Administrate
  class Namespace
    private

    ##
    # Extends the route discovery that Administrate uses to skip
    # any routes that have an "administrate: false" key.
    # This allows for controllers to exist within the Administrate
    # namespace without them needing to have corresponding dashboard
    # objects.
    def all_routes
      Rails.application.routes.routes.reduce([]) do |routes, route|
        next routes unless route.defaults.fetch(:administrate, true)

        routes << route.defaults.values_at(:controller, :action).map(&:to_s)
      end
    end
  end
end
```

This modification makes Administrate ignore any routes in the route namespace (e.g. `admin`) that have an additional `administrate` option set to `false`, for example:

``` ruby
namespace :admin do
    resources :users do
      resources :password_resets, only: :create, administrate: false
    end
end
```

- will allow administration of users, but will not trigger Administrate behaviour for password resets.

I hope this is helpful!

**Comment by donatoaz** [comment]
Not too late at all! Thanks for the tip. I was doing a nasty workaround by overriding _navigation.html partial as such:

```haml
%nav.navigation{role: "navigation"}
  - Administrate::Namespace.new(namespace).resources.each do |resource|
    - next if display_resource_name(resource) == 'Sessions'
    - next if display_resource_name(resource) == 'Hotspots'
    = link_to(display_resource_name(resource), [namespace, resource_index_route_key(resource)], class: "navigation__link navigation__link--#{nav_link_state(resource)}")
  = link_to(t('logout'), admin_logout_path, method: 'DELETE', class: "navigation__link navigation__link")
```

I think your solution is elegant, so I'll be closing this issue. Perhaps you should consider submitting this as a PR.

**Comment by donatoaz** [comment]
If you don't mind, where did you place this code?

**Comment by joshmcarthur** [comment]
@donatoaz I put it in `lib/administrate_ext.rb`, and then added `config/initializers/administrate.rb` that had `require Rails.root.join("lib", "administrate_ext")` inside it.

Just a small gotcha I've discovered since this morning - RSpec controller tests (so probably also Test::Unit controller tests) seem to require all route params to be passed through in order to match the route, even if the route has a default value.

Just as an example, using the route I used in my first comment:

``` ruby
namespace :admin do
    resources :users do
      resources :password_resets, only: :create, administrate: false
    end
end
```

The RSpec request has to be made in the following way to match the route:

`post :create, params: { user_id: 1, administrate: false }`

This is JUST for tests, and is not required for the route to work in "real life". 

Because of this, I'm not sure if this change is suitable for a pull request. I can't think of any other way off the top of my head to communicate data about a route back to administrate though, without introducing named route helpers like `devise_for` - which I don't feel should be part of administrate. 

Hopefully this thread is helpful to others!

**Comment by donatoaz** [comment]
Thanks, I was having issues, perhaps due to load ordering, doing this monkey patching from within my app folder. I put them on lib/ext and switched to loading them on an initializer like you done so.

Now that you mention, I also have devise_for routes and could not get entirely rid of my `_navigation.html` hack.

With regards to testing, I do not do controller testing, I only do request tests, so instead of

```
post :create, params: { ... }
```
I do 
```
post "/api/locations", params
```

and that works out just fine
