### ISSUE TITLE
Lazy load administrate dependency

### ISSUE THREAD

**Issue by lgsanjos** [thoughtbot/administrate#1354]
After profiling the load time of my rails app one of the gems that showed up was administrate, and seems to be an easy one to tackle.

* I changed the Gemfile to be like `gem 'administrate', require: false`
* My unit tests and most feature specs continued to work, cause they don't need the gem to be loaded, which is a win.
* Added `require 'administrate'` on my admin/controllers but it doesn't load the gem entirely.

The error I got when rendering the page is:
`The action 'index' could not be found for Admin::UsersController`

I tried many ways to require all the administrate files, even brute forced:
`Gem.find_files('administrate/**/*.rb').each { |path| require path }`

No luck yet, any ideas?

**Comment by GeoffAbtion** [comment]
What does the rest of the error stack trace look like?

What does your `Admin::UsersController` definition look like?

**Comment by pablobm** [comment]
This one has been silent for a while. I think we can close it. Please let us know if you think otherwise.

**Comment by sfcgeorge** [comment]
Same issue. Administrate is slow to require because there's quite a lot of code in there. Moreover you may not need to use all of it, like the Pundit concern for example, but it all gets loaded anyway even if it's not used.

`gem 'administrate', require: false` won't currently work.

Here's how I think it should work:

* Doing `gem 'administrate'` causes Bundler (RubyGems?) to automatically `require "administrate"` if it exists (it does).
* That file then calls `require "administrate/engine"` to set register things with rails and require everything else.

So you should be able to either `require "administrate"` or `require "administrate/engine"` inside an admin controller and that would only load Administrate at that point. 

Or in my case I don't want asset pipeline stuff so I copy paste the contents of `engine.rb` into an initializer and comment out the requires I don't want.

Problem is Zeitwerk complains `Administrate::ApplicationController` can't be found. And requiring it directly doesn't work (either as a normal `require` or via `Gem.find_files` — file not found. The file is there if you use command line `ls` on the gem folder, but Bundler/RubyGems override `require` to do their own thing.

Manually copy pasting application controller gets you a little further, but then helpers are missing, so you have to copy over that file and then views are missing. So that's not practical.

The issue I believe is this line in gemspec https://github.com/thoughtbot/administrate/blob/main/administrate.gemspec#L1 which seems to only expose the contents of `lib` to require and not the contents of `app`.

I think an easy improvement would be adding "app" to that line.

Ideally though Administrate would be smarter about how much it loads — the gem promises modularity and is so close to meeting that. Perhaps explicit requires throughout rather than globbing would do it.

**Comment by pablobm** [comment]
@sfcgeorge - Would you be able to create a PR and we can have a look at how it would work?
