### ISSUE TITLE
Documentation missing: Customize Attribute Partials

### ISSUE THREAD

**Issue by estiens** [thoughtbot/administrate#137]
`Internal Server Error` at: https://administrate-docs.herokuapp.com/customizing_attribute_partials

**Comment by graysonwright** [comment]
@estiens thanks for pointing that out - we removed that documentation a little while ago. Where did you follow the link from?

**Comment by graysonwright** [comment]
We moved it because of similarities with https://administrate-docs.herokuapp.com/adding_custom_field_types

In retrospect, they are describing different customization workflows, so it makes sense to keep both. I've reverted the commit that removed that doc, so it should be accessible now.

Thanks for pointing that out!

**Comment by estiens** [comment]
Looks great, it was followed from: https://administrate-docs.herokuapp.com/adding_custom_field_types
