### ISSUE TITLE
fields: Checkbox field with >2 options?

### ISSUE THREAD

**Issue by conwayanderson** [thoughtbot/administrate#1516]
I have multiple checkboxes for one of my fields. I'm trying to reproduce this in the edit view of the dashboard but haven't figured it out after reading through the docs.

The form view I was trying to reproduce shows a series of checkboxes and the user can select multiple options. The selected options are stored as an array.

I'm new to administrate and not a very experienced programmer. I assume there's something I'm missing? Also checked Stackoverflow and didn't find anything.

**Comment by pablobm** [comment]
Hello @conwayanderson. Would you be able to create a question for this on StackOverflow, providing the following details?

* Type of the field. For example, the migration introducing it, or the relevant table description from the `config/schema.rb` file.
* A screenshot of the field (if shown anywhere else in your application), or a mockup of what you expect to see.

(Asking for StackOverflow because it's a more appropriate place for this question, and other people may benefit better from the answer there).

Leave a link to the question here and I'll have a look.

Thank you!

**Comment by conwayanderson** [comment]
Of course! Thanks for looking into this. Here's a link to the SO question:
https://stackoverflow.com/questions/59603937/how-do-you-display-multiple-checkbox-fields-in-the-edit-view-of-the-administrate

**Comment by b4thestorm** [comment]
hi @conwayanderson , 
 
In order to make the checkbox fields accessible in your edit form, you will have to create a Custom Field type for your checkboxes. in this case, mine is employment type.

<img width="1046" alt="Screen Shot 2020-01-07 at 1 17 27 AM" src="https://user-images.githubusercontent.com/4723872/71872807-7cf37800-30eb-11ea-97ef-ce619a65dfde.png">


step 1) run rails generate administrate:field employment_type
   that will create these files: app/fields/employment_types_field.rb
                                                app/views/fields/employment_types_field/_show.html.erb
                                                app/views/fields/employment_types_field/_index.html.erb
                                                app/views/fields/employment_types_field_field/_form.html.erb

step 2) edit the custom field class in the newly generated folder, fields/employment_types_field like this: 
<img width="490" alt="Screen Shot 2020-01-07 at 1 02 13 AM" src="https://user-images.githubusercontent.com/4723872/71872098-5e8c7d00-30e9-11ea-97fa-ff595eefdb5b.png">
(I opted to create a db table + model for holding Employment Categories and return all categories)

step 3) go to app/views/fields/employment_types_field_field/_form.html.erb 
    and create the checkboxes using the field.employment_types in this form partial. 
   (field is an object of type(EmploymentTypesField))
<img width="731" alt="Screen Shot 2020-01-07 at 1 08 49 AM" src="https://user-images.githubusercontent.com/4723872/71872397-4832f100-30ea-11ea-8335-d38e92f88dfb.png">

step 4) next include the custom field type in the dashboard file you want to show the field at. 
  For me, I wanted to show it in customer_dashboard.rb. You will have to add the field type in 2 
  places, in the ATTRIBUTE_TYPES constant hash and then also in the FORM_ATTRIBUTES array. 
<img width="599" alt="Screen Shot 2020-01-07 at 1 13 21 AM" src="https://user-images.githubusercontent.com/4723872/71872625-02c2f380-30eb-11ea-845a-f48173499868.png">

step  5) Last step you will have to go to the admin controller for the dashboard whose form you just modified. you will have to override the Update action in the controller. In this case, you will simply need to modify the strong params being passed to the update action to account for the checkbox input. 
<img width="837" alt="Screen Shot 2020-01-07 at 1 16 49 AM" src="https://user-images.githubusercontent.com/4723872/71872778-677e4e00-30eb-11ea-98fb-0683ca20fee4.png">

that should be it.

**Comment by pablobm** [comment]
That's two answers now 😄 (one here and another one on Stack Overflow). I hope that helps!
