### ISSUE TITLE
Dynamic select field

### ISSUE THREAD

**Issue by bekicot** [thoughtbot/administrate#1535]
* What would you like to be able to do? Can you provide some examples?
This should be the simpler case
```ruby
Field::Select.with_options(collection: [Time.current])
```
another case is if we want to keep the list up to date. e.g via database record

* How could we go about implementing that?
I think by adding another parameter type, it should be something like lambda would be enough to solve the problem.

* Can you think of other approaches to the problem?
No other approach. as to my knowledge.

**Comment by pablobm** [comment]
A way to do this would be to implement a new field type, probably inheriting from `Administrate::Field::Select`, like this:

```ruby
# /lib/administrate/field/relative_day_select.rb
module Administrate
  module Field
    class RelativeDaySelect < Field::Select
      def selectable_options
        [
          ["Today", Date.today],
          ["Tomorrow", Date.tomorrow],
        ]
      end
    end
  end
end
```

```ruby
# /app/views/fields/relative_day_select/_form.html.erb 
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.select(
    field.attribute,
    options_from_collection_for_select(
      field.selectable_options,
      :second,
      :first,
      field.data.presence,
    )
  ) %>
</div>
```

```ruby
# /app/views/fields/relative_day_select/_show.html.erb 
<%= field.data %>
```

```ruby
# /app/views/fields/relative_day_select/_index.html.erb 
<%= field.data %>
```

Does that help?

**Comment by bekicot** [comment]
@pablobm That would help a lot. But just wondering, does this feature request shall be implemented in the select field instead? I think it is okay to add an option for the user to choose whether they want constant select options or dynamic select options. The drawback I could think of is a little bit of performance degradation on checking whether the expected option is a lamda or not.

If you think it is okay to add such functionality, I can make a pr for it. After working on #1517

**Comment by pablobm** [comment]
I think it's ok. I don't think it would cause any performance degradation.

Ideally, I think a solution should be inspired by Rails's [`options_from_collection_for_select`](https://api.rubyonrails.org/v5.2.4.1/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-options_from_collection_for_select), to minimise maintenance effort as well as avoid introducing new conventions. What do you think?

**Comment by pablobm** [comment]
To clarify: try a PR and I'll have a look.

**Comment by nickcharlton** [comment]
@bekicot, were you able to open a PR for this?

**Comment by sedubois** [comment]
NB: unfortunately I do not benefit much from this PR because ActionView's `collection_select` already accepts a `proc` but as Administrate does not have this field type I had to build my own starting off from [this outdated one](https://github.com/headwayio/administrate-field-collection_select).

From the [`ActionView::Helpers::FormOptionsHelper#collection_select`](https://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html) documentation:
> The <tt>:value_method</tt> and <tt>:text_method</tt> parameters are methods to be called on each member of +collection+. The return values are used as the +value+ attribute and contents of each <tt><option></tt> tag, respectively. They can also be any object that responds to +call+, such as a +proc+, that will be called for each member of the +collection+ to retrieve the value/text.

Even with this PR improvement I need to keep using my own custom field because it also uses Selectize and supports `multiple`.

This might illustrate that the separation between "core"  and "external" Administrate code is not so straightforward:
- people can create their own plugins and share them on the [list of plugins wiki page](https://github.com/thoughtbot/administrate/wiki/List-of-Plugins), but that information tends to be outdated or not verified and so the quality information gets diluted;
- external plugins might not be as stable as Administrate itself, because people are basically on their own and e.g. cannot ask for their PRs to be reviewed by other Administrate users (and the wiki page itself is not subject to a review process);
- various users (such as myself) might have functional custom administrate fields in their own private systems but have no clue how to turn that into a gem;
- even if one finds an external plugin that is functional, it does not benefit from a clear API documentation like the ["official" API documentation](http://administrate-prototype.herokuapp.com/);
- the documentation of these external plugins is fragmented (not available from the same central place);
- we might also end up in situations where an external plugin already addresses a need, but due to lack of visibility then we try to address the need internally (e.g. this PR), which defeats a bit the purpose of supporting external plugins.

Maybe the documentation system could integrate external plugins as well...

**Comment by nickcharlton** [comment]
@sedubois, could you open a new issue for that so we can keep track of it?

**Comment by sedubois** [comment]
@nickcharlton sure, but as I mentioned quite a few things could you say which part you think constitutes the issue that I should create? Do you mean that we should add a support for `collection_select` or are you referring to my other ramblings?

**Comment by bekicot** [comment]
@sedubois I agree that we should have some kind written convention. I also agree that we should have a defined scope of what what the administrate trying to achieve and let plugins to solve other problem, that is not defined in the scope.

However, don't you think this is not relevant to this issue? Since you are the first one that made the point and found out that it is useful to have such a documentation system, it would be best for you to open a new issue for that. And discuss further in the newly created issue.

We may have a written 1.0 milestone that is usefull for us.

**Comment by sedubois** [comment]
@bekicot yes let's create a new issue, will just wait for @nickcharlton's feedback to see what its scope should be.

**Comment by nickcharlton** [comment]
I think you should open a new issue for `collection_select` (it's in `ActiveView`, perhaps core should support everything that does?).

I'm going to pull your other comments and open a documentation meta issue, as this is something I want to focus on and it provides a good starting place. Thanks!
