### ISSUE TITLE
Smart Searching

### ISSUE THREAD

**Issue by graysonwright** [thoughtbot/administrate#157]
The long-term plan for the search bar is to support structured queries, to allow people to do complex searches over the data from a single field.

We'd like to support:
- Searching numeric fields for values greater than, less than, or equal to a given number
- Searching text fields for text including a given string
- Searching boolean fields by `true` or `false` value
- More than one of these ^ in the same search

Bonus points for a scheme that will let us search custom field types using dev-defined strategies.

I want to open up a discussion about the best way to structure the search queries.
- If you know of other apps or projects that do multi-field search well, please share them for inspiration.
- If you have an opinion on what the query structure should look like, chime in!

**Comment by danbee** [comment]
I wonder if the whole search functionality should stay simple, but had some hooks to enable the dev to integrate more advanced search.

For example, if the app already has search implemented using something like Elasticsearch it would be better if there was an easy way to integrate that rather than having another search mechanism.

**Comment by thorncp** [comment]
What do you about making the first step be a controller method that's overridable? I'm currently searching a polymorphic association, which requires some hand holding, and I have to override the action to replace Administrate's [default search](https://github.com/thoughtbot/administrate/blob/01e125c/app/controllers/administrate/application_controller.rb#L5). If this happened in a method, e.g. `search_resources`, I could override that with my custom thing.

**Comment by graysonwright** [comment]
@thorncp I like that a lot. Right now there's a lot going on in the index method, and that would be a good first step towards breaking it out.

**Comment by mikecx** [comment]
I agree the controller method override for search would definitely work. I currently use Elasticsearch mixed with Searchkick but I know there are probably 100 other solutions out there so there's a big need to remain very generic.

The thoughts of filtering came up with issue #183 which definitely complicate the search "chain". In my instance, I currently pass the filters as where clauses to Searchkick/Elasticsearch but that's obviously not a generic enough solution for what Administrate hopes to accomplish. 

A potential better solution might be to provide documentation and create a clean way to override the Administrate::Search class. Giving clean methods in there for both searching and filtering reduces the places to override (1 instead of per controller), gives places for query & filter (any anything else that might not have been thought of yet), and keeps the logic in one place.

**Comment by 5minpause** [comment]
Having the search bar support structured queries sounds like a good idea for developers. We use ActiveAdmin as a dashboard in our custom CMS. So it's user-facing for editing pages and resources. Our users like the filters/scopes that ActiveAdmin provides and which can be extended. How could a similar feature be integrated into Administrate?

![screen shot 2015-11-11 at 10 56 53](https://cloud.githubusercontent.com/assets/84148/11088492/f9a1a682-8862-11e5-8308-cb9e6630768e.png)

**Comment by nando** [comment]
Hi,

i've just made this PR of a feature that lets you specify a model scope ending the search text with a colon (e.g. "sent:"):

https://github.com/thoughtbot/administrate/pull/276

Have a nice weekend!!!
-- nando

**Comment by nando** [comment]
https://github.com/thoughtbot/administrate/pull/276

**Comment by kubenstein** [comment]
im also struggling with custom search. was thinking that if `Administrate::Search` is passed as a param to index action, someone can provide its own custom searcher, so something like this:
```ruby
module Administrate
  class ApplicationController < ActionController::Base
    def index(searcher = Administrate::Search) 
      #...
      resources = searcher.new(resource_resolver, search_term).run 
      #...
    end
#...
end
```
and custom controller:
```ruby
module Admin
  class CustomController < Admin::ApplicationController
    def index
       super(MyCustomSearcher)
    end
  end
end
```

**Comment by gabrielrios** [comment]
I don't think rails Actions accepts params. I guess the way to do it here
is have search be an instance method that we could override. That's exactly
what I did with the "resolver" so I could have controllers scopes to the
current user
Em ter, 22 de mar de 2016 às 04:28, Jakub Niewczas <notifications@github.com>
escreveu:

**Comment by conradbeach** [comment]
@nickcharlton Any interest in adding more advanced searching to administrate? Would you be open to accepting PRs for this?

**Comment by gabrielgarza** [comment]
+100 for smart searching

**Comment by purinkle** [comment]
@graysonwright, is this still an issue for you?
