### ISSUE TITLE
License link on heroku front page returns 404 error

### ISSUE THREAD

**Issue by timando** [thoughtbot/administrate#1645]
On `https://administrate-prototype.herokuapp.com/`, if I try to click the license link, it gives a 404 error.
This also happens with the contributing guide.

**Comment by nickcharlton** [comment]
Ah I see! It's likely because they have a file extension and we assume that pages don't.

The relevant code is here: https://github.com/thoughtbot/administrate/blob/0e7e4ecba582bf2e026a0a1eb6537e3239793d60/spec/example_app/app/controllers/docs_controller.rb#L34-L36

There's some weirdness caused by linking for both the purposes of GitHub (where the links in the README should work) and also on the documentation site and we're tried to not duplicate them. An option here would be to have a special case for each of these two links.

Do you think you'd be able to open a PR to make something work here?

**Comment by timando** [comment]
I'll have a play with it on the weekend.
