### ISSUE TITLE
Bulk add by providing a quantity

### ISSUE THREAD

**Issue by netfirelabs** [thoughtbot/administrate#1724]
Does administrate provide an option to enter the number of rows you want to create in db and generate the rows in bulk? 

For example, 

i want to provide an option to create multiple coupon codes all at once, the `coupon_code` column can be randomly generated alphanumeric string and user should have an option that says "how many coupon code you want to create"

**Comment by pablobm** [comment]
There isn't such an option unfortunately. Creating an interface like you describe in a way that it's generic enough for everybody is difficult, and it's not in the horizon at the moment.

Having said that, it's possible for you to customise your setup to support this. Here's how I would do it:

1. Override the `index` view to add the form you describe. See http://administrate-prototype.herokuapp.com/customizing_page_views for how to do this.
2. Add an action to handle submission of this form in your controller (probably in `Admin::CouponsController` in your case).

I'm going to close this for now. Let us know if you think otherwise.
