### ISSUE TITLE
View Component instead of administrate fields

### ISSUE THREAD

**Issue by pedrocarmona** [thoughtbot/administrate#1750]
Administrate fields look a lot like components.

Idea: use https://github.com/github/view_component instead of administrate fields.

* What would you like to be able to do? Can you provide some examples?

  All fields should be view components, easier to add new fields, to test them and less code to maintain.
  Would make Administrate even more Rails native.

* How could we go about implementing that?

  (still thinking)

* Can you think of other approaches to the problem?

  Rails Versions:
   
   - “ViewComponent is supported natively in Rails 6.1, and compatible with Rails 5.0+ via an included monkey patch.” in ViewComponent's Readme
  - Currently Administrate master depends on 5.0+ already.
  - Would require all rails projects between >=5.0 and <6.1 to use the monkey patch. But then again, its not hard to transition from 5.0 to 6.0

**Comment by pablobm** [comment]
Hello @pedrocarmona. Thank you for your suggestion. This looks good and I wasn't aware of it. I may experiment with it personally.

However I don't think we'll be bringing it into Administrate any time soon. We currently have some issues with fields, but not the sort that (from what I see) would be fixed by turning them into view components. For example, testing associative fields is tricky because it involves detecting associations and working with ActiveRecord. I want to revisit this to see how this could be redesigned for better encapsulation. Eventually we may get there and get to a point where the top problem is the one solved by view_component. However it will be a while until this happens.

**Comment by pablobm** [comment]
Closing for now, but happy to hear more suggestions.
