### ISSUE TITLE
How to do file processing / parsing? 

### ISSUE THREAD

**Issue by janosrusiczki** [thoughtbot/administrate#1756]
Say I have a model which has a field that would be populated by uploading a file and then doing some processing / parsing on it to get the data needed for that field. How do I accomplish this with administrate?

**Comment by janosrusiczki** [comment]
My idea would be to create a file field, as I'm already using the [shrine gem](https://github.com/shrinerb/shrine) for uploading images on other models, store the uploaded file and do the processing on it on a model callback or redefine the controller actions in administrate.

Is there a way to do it without storing the file?

**Comment by pablobm** [comment]
@janosrusiczki - To me it sounds like you should override the `create` and `update` methods of the controller to process those files and save those records as appropriate.

At the end of the day, Administrate tries to do as little as possible, making it so that dashboards can be customised using Rails's own conventions as much as possible. So for example, any of the controllers generated from Administrate inherits from https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb. In turn this defines the default `create` and `update` methods. Here's one of them:

https://github.com/thoughtbot/administrate/blob/5a5db7de78ebd63e17e2e6105897b59eb8467758/app/controllers/administrate/application_controller.rb#L43-L57

If you override these (perhaps calling `super` at some point, although not required), then you should be able to get the behaviour that you ask.

Does that make sense?

**Comment by janosrusiczki** [comment]
Thanks, I will give it a try.
