### ISSUE TITLE
Feature Request: Redirect search if only 1 result

### ISSUE THREAD

**Issue by kevintraver** [thoughtbot/administrate#1795]
It would be awesome to have the ability to redirect the search when there is only 1 result.

Perhaps this could be opt-in functionality since this might be non-standard behavior.

Could be something like this in the `ApplicationController`

```
def index
  if resources.one?
    redirect_to( [namespace, resources.first] )
  else
    ...
  end
end
```

**Comment by c4lliope** [comment]
Ooh - i like your idea.

This feature could pose a problem when someone is searching for something other than the one result they see.
In that case, they would immediately want to search again for their original goal,
but because of the redirect, there would no longer be a search bar onscreen.

So, as an example on the [demo page](https://administrate-prototype.herokuapp.com/admin) -
searching "Mark" when there is only one mark in the system currently goes here,
![Screen Shot 2020-10-13 at 11 41 46 PM](https://user-images.githubusercontent.com/30454698/95940993-aee9e700-0dad-11eb-9443-2c66464a5468.png)
and this feature would redirect here -
![Screen Shot 2020-10-13 at 11 42 17 PM](https://user-images.githubusercontent.com/30454698/95941020-c032f380-0dad-11eb-8273-8e3e44b33bbe.png)

If you proceed, i think you'd have to add a couple things to the customer page for Garfield Marks:
1. re-render the search box with the user's query in it, so they can quickly change their query and re-run if they were searching for someone else.
2. add a flash message or other note, saying "your query only pulled up only one record." - so we don't confuse anyone too much when they upgrade their dashboard.

**Comment by kevintraver** [comment]
I like the idea of a flash message on redirect to help avoid any confusion.

**Comment by kevintraver** [comment]
That is a good point. I figured others could find this useful in the future. Thanks!
