### ISSUE TITLE
Polymorphic many to many relations 

### ISSUE THREAD

**Issue by frostmark** [thoughtbot/administrate#1807]
Hey. I would like to have a polymorphic select field for the following case:

```ruby
class Movie < ApplicationRecord
  has_many :genre_resources
  has_many :genres, through: :genre_resources
end

class GenreResource < ApplicationRecord
  belongs_to :genre
  belongs_to :resource, polymorphic: true
end

class Genre < ApplicationRecord
  has_many :genre_resources
  has_many :resources, through: :genre_resources
end

```
I want to be able to select genres for movie/etc. Currently, I haven't found a solution for this

**Comment by frostmark** [comment]
I guess we just should extend `Field::HasMany`

**Comment by pablobm** [comment]
So I understand that you want a multiselector for genres in the Movie dashboard. Is this correct?

From looking at these associations, I would expect the multiselector to be for genre resources instead. You can't just select a genre for a movie because there will be several genre resources that can make it happen. Choosing the right ones would require additional logic (and perhaps even interface elements) that Administrate can't provide because it doesn't know your application.

I'm going to close this for now, as I don't think it's an Administrate issue, and I don't think there's a generic field type that we can provide to help with it. Feel free to provide more information if you think it's relevant.

**Comment by frostmark** [comment]
I mean that Genre can be bind with any :resource (for example Movie, Game etc)

**Comment by frostmark** [comment]
But okay, I think that I can resolve this problem outside the Administrate gem

**Comment by pablobm** [comment]
@frostmark - Sure it can, but which one?

Say you are looking at the Movies dashboard. There's a selector for genres. What does it look like? When you select a genre, how does it know which GenreResource to select with it?

**Comment by frostmark** [comment]
That should look like the usual `has many` selector.

`GenreResource` depends on the resource wich which you bind it. If we are selecting genres for `Game`, then `GenreResource` will have `resource_type — Game`, or if we are selecting for `Movie`, then relations `GenreResoruce` is created with `resource_type — Movie`


PS.
GenreResoruce has the following structure:

```ruby
  create_table "genre_resources", force: :cascade do |t|
    t.bigint "genre_id"
    t.string "resource_type"
    t.bigint "resource_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["genre_id"], name: "index_genre_resources_on_genre_id"
    t.index ["resource_id", "resource_type", "genre_id"], name: "polymorphic_genre_many_to_many_resource_idx"
    t.index ["resource_id", "resource_type"], name: "polymorphic_genre_resource_idx"
    t.index ["resource_type", "resource_id"], name: "index_genre_resources_on_resource_type_and_resource_id"
  end
```

We can have one genre in different resources (Game, Movie as I wrote above)


----

I hope that I've been clear 😄

**Comment by DavidGeismarLtd** [comment]
@frostmark Im interested in the way you solved this if you did !

**Comment by pablobm** [comment]
Let's say we have the following records in the DB:
```
Genres
  Western
  Sci-Fi

Genre resources
  Cowboy hat - belongs_to Western
  Rocket - belongs_to Sci-Fi
  Revolver - belongs_to Western
```

We want to create a movie called "Toy Story", with this structure:

```
Movie: Toy Story
  has Genre resources:
    - "Cowboy hat" image (in turn belongs_to Western)
    - "Rocket launch" video (in turn belongs_to Sci-Fi)
```

Let's say we go on our Administrate dashboard and create a movie "Toy Story". Next we want to replicate the above.

We edit "Toy Story" and select a genre. The genres available are "Western" and "Sci-Fi".

If I select "Western", what genre resources will "Toy Story" get? An option will be to assign it all the genre resources linked to "Western", but this would assign the "Revolver", which we don't want on "Toy Story".

It's for this reason that what this issue describes can't be a generic selector. There must be some additional constraints in your app that are not explained here.

Instead, I would expect the user to select a "genre resource" for a movie, which would implicitly select a "genre".

**Comment by pablobm** [comment]
Thank you for the explanation @DavidGeismarLtd. It helps seeing some real use cases to understand the problems that users of Administrate want to solve.

One thing I'm missing: where exactly is the polymorphism in your example? It looks like `Program` is an `Argumentable`, but I'm not sure. Or perhaps there isn't polymorphism (as exactly defined by Rails) and yours is simply a similar example.

In any case, in your specific example, the problem I see is with `ArgumentArgumentabletype#argumentable_type`. Administrate can't make a decision automatically as to what the value should be, because it depends on your app.

I think that the solution here is to use a `HasMany` field, but then add custom code in either the controller (`Admin::ArgumentableController#update` and `#create`) to insert the desired value for `argumentable_type`. Or perhaps this custom code could go at the model level. But I'd have to know more about the use case to know. Would one of these work?

When you say "with the current program as the resource_type", do you mean that `Argumentable#resource_type` should be the value used for `argumentable_type`?
