### ISSUE TITLE
Resources doesn't generate edit/create routes unless passing it into only:

### ISSUE THREAD

**Issue by andrewdang17** [thoughtbot/administrate#1823]
* **What were you trying to do?**
After running the `rails generate administrate:install` command and seeing `resources: :some_model` in my `routes.rb` file, I expected the new/edit routes to show up as expected from the [rails docs] (https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions) and also since there's nothing in the documentation saying I need to generate these views/routes.

* **What did you end up with (logs, or, even better, example apps are great!)?**
With the install command, I only get index/create/show/update/destroy routes, however if I change my resource routing to the below they all show up.
```
resources: :some_model, only: %i(index show new create edit update destroy)
``` 

I created a new rails app just to see if this is due to my app but I get the same problem on the new one as well.

* **What versions are you running?**
  - Rails: 6.0.3.4
  - administrate: 0.14.0

possibly unrelated but I run into this bug as well https://github.com/thoughtbot/administrate/issues/1366 when passing in `only:` to the `resources` method

**Comment by pablobm** [comment]
Thank you for raising this. This behaviour is indeed incorrect so it could be a bug, but it's strange. What do you exactly see when you are not using `only`? Is it a `Routing Error` with message "No route matches..."? Could you please paste it here? Can you paste an example routes files that has this problem? The one from your example Rails app would be enough.

I also noticed that your code has a slight misspelling: it should be `resources :some_model` instead of `resources: :some_model` (no colon at the end of `resources`). I assume this is just a transcription mistake while you were describing the bug, and not copied verbatim from your routes. Am I correct?

**Comment by andrewdang17** [comment]
@pablobm Thanks for getting back quickly! Turns out I still had ` config.api_only` set to true still which doesn't generate the view routes as expected so this bug can be closed. Although it is odd they get generated when passing in the `only: [:new, :edit]`

**Comment by pablobm** [comment]
That's odd indeed. Thank you for letting us know. I may dig into it if I get a moment.

**Comment by pablobm** [comment]
OK, after re-reading, all makes sense.

As you say, `api_only` apps do not generate `new` and `edit` routes. That makes sense as these are non-essential routes that only provide an HTML form.

Adding `only: [:new, :edit]` to the `resources` line appears to add these routes. I would have thought it it acts as a filter applied to the list of routes, but the internal implementation in Rails must be different, and it ends up signalling that the routes be added, rather than kept if existing.

Anyway, that's it :-)
