### ISSUE TITLE
Can I use actiontext/trix editor for e.g. a blog post body field?

### ISSUE THREAD

**Issue by la-ruby** [thoughtbot/administrate#1825]
![image](https://user-images.githubusercontent.com/55279023/98390310-07598080-200a-11eb-8c5c-a74821b938b9.png)

If it's not something administrate provides out of the box, how would one go about adding this "feature"

**Comment by pablobm** [comment]
It should be possible to do this. You'll need to provide JavaScript code that activates the rich text editor, and perhaps a custom field instead of the default `Field::Text`, depending on whether you need changes to the markup of this one.

To add custom JS, check out the documentation on [how to customize views](http://administrate-prototype.herokuapp.com/customizing_page_views). Pay special attention to the section "Customizing layouts".

If a custom field is needed, you can read the documentation on [how to add custom field types](http://administrate-prototype.herokuapp.com/adding_custom_field_types). You'll probably be able to simplify by inheriting from the existing `Field::Text`.

Since this is a question about existing functionality, I'll close this issue. If you have more questions, I suggest asking at [Stack Overflow](https://stackoverflow.com) (use the labels `ruby-on-rails` and `administrate`), as it may be easier for others to find the answers. I keep an eye there for people asking questions.

**Comment by bradonomics** [comment]
@la-ruby, were you able to get this working? I'd like to achieve the same but have been unable to do so. I tried [Chris Oliver's tutorial](https://www.youtube.com/watch?v=gKEUyzfIJpM), but I guess things have changed with Rails 6.

**Comment by la-ruby** [comment]
i couldn't properly try it out at the time, and nowadays im stuck with activeadmin
