### ISSUE TITLE
Feature Request: Batch Editing

### ISSUE THREAD

**Issue by mikecx** [thoughtbot/administrate#184]
Batch editing, like what's provided by active_admin is a big feature that seems to be missing in administrate for now.

**Comment by javierjulio** [comment]
Nice, I wanted to post about this too. Would this be a welcome feature? I'd be happy to contribute on this or something else.

**Comment by 5minpause** [comment]
Batch editing is definitely a feature that seems necessary. Coming from ActiveAdmin it will be something our clients expect.

**Comment by graysonwright** [comment]
oh, interesting. I wasn't aware ActiveAdmin had this. Let me play with their implementation a bit and see what the best way forward is.

**Comment by 5minpause** [comment]
Sounds like a good idea. If you need some practical examples, let me know.

**Comment by graysonwright** [comment]
Yeah, I think this is something that we should approach from a design perspective - a great first step would be gathering examples of batch-editing flows that people enjoy.

If you know of a system that has good batch-editing support, post a link/screenshot/gif!

**Comment by hughfm** [comment]
Would find this very useful. At least the ability to batch destroy from index pages is very handy in ActiveAdmin...

**Comment by thecalliopecrashed** [comment]
Alright, there hasn't been much movement on this conversation, but it seems like there is some general interest.

First step is to design the behavior... check boxes? click-shift-click?

It seems like Google Inbox has a really smooth implementation, so maybe we can start from that and work backwards into code.

**Comment by pablobm** [comment]
If we were to provide this, we would need to study some use cases and think it through. It could be done in many ways, each with a different behaviour and user experience. Not something that we can just "implement".

Initially I would prefer if Administrate didn't implement this, but instead it provided the APIs to enable users to create this interface as appropriate for their own use cases. Actually, we may have this already. Not necessarily easy to do, but I think it's possible. I'll explain.

It might be possible to do this by overriding templates and controllers, the way that Administrate already allows. For example, client code could override templates (providing checkboxes, buttons, etc), provide custom forms with the appropriate fields and behaviour, and control the process with custom actions in the admin controllers.

I think I would like to see some examples of this first, so that we can start identifying patterns, and work to make the experience simpler for other users in the future.

But for now, we have had no input, and this work feels a long way down the road. I'm closing this issue as it's unlikely to move forward for the foreseeable future. If anyone wants to provide these examples and ideas, do continue adding your comments here and perhaps this situation will change.

**Comment by c4lliope** [comment]
Sounds like a good decision.

**Comment by andreibondarev** [comment]
We rolled out a plugin to accomplish simple batch editing functionalities: https://github.com/SourceLabsLLC/administrate_batch_actions. The demo section showcase batch resource deletion. Any feedback, ideas or contributions are welcome!
