### ISSUE TITLE
Scope a belongs_to field based on the value of the previous field

### ISSUE THREAD

**Issue by gustavothecoder** [thoughtbot/administrate#1887]
Hi,

I have a dashboard with these attributes:

``` Ruby
ATTRIBUTE_TYPES = {
  id: Field::Number,
  farmer: Field::BelongsTo,
  property: Field::BelongsTo,
  created_at: Field::DateTime,
  updated_at: Field::DateTime
}.freeze
```

And in the forms of this dashboard (`new` and `edit`), i would like to list the properties based on the selected farmer. For example, if the selected farmer is John, I would like to list all of John's properties and not all the properties of all the farmers.

Is there any way I can do that?

Thanks in advance.

**Comment by pablobm** [comment]
Unfortunately, Administrate doesn't support this at the moment. Adding explicit support would also be quite tricky at the moment, as this feature would involve dynamic behaviour: the options for `property` would change immediately as `farmer` changes. Currently Administrate doesn't have any such dynamic features, and all JS is merely enhancing existing HTML markup.

Having said that, I think you might be able to implement this by providing your own JS. It would go something like this:

1. On page load look this `farmer` field and listen to changes. Internally, `BelongsTo` fields are enhanced with [Selectize](https://github.com/selectize/selectize.js/blob/master/docs/api.md), so you'll want to have a look at its documentation.
2. When `farmer` changes, make an Ajax request to an endpoint provided by your app, where the new options for `property` can be retrieved.
3. Again, use the Selectize API to change the options of the target field.

There's an existing plugin that, although not doing the same, may provide some pointer on how to implement all that: https://github.com/fishbrain/administrate-field-belongs_to_search

Apart from that, this is not really an issue with Administrate at the moment. Our current roadmap (as it were) doesn't contemplate adding functionality for this, and the above should be a solution, so I'm going to close the issue. Do let us know if you think otherwise.
