### ISSUE TITLE
Field::Belongs_to not work as expected

### ISSUE THREAD

**Issue by df1228** [thoughtbot/administrate#1918]
* What were you trying to do?

Use Field:Belongs_to field in `item_dashboard.rb` like this:

```
    upload_by: Field::BelongsTo.with_options(:class_name => "User", :foreign_key => "upload_by"),
```

* What did you end up with (logs, or, even better, example apps are great!)?
<img width="1399" alt="Screen Shot 2021-02-25 at 9 21 06 AM" src="https://user-images.githubusercontent.com/40170414/109088658-ccab5d80-774a-11eb-96b6-1d7d39dad486.png">

* What versions are you running?
  - Rails: 6.1.1
  - Ruby: 3.0.0
  - administrate: current master branch

**Comment by pablobm** [comment]
Unfortunately, we need more information in order to know what's going on. From what you show, I see that there are two models involved: `Item` and `User`. What do they look like (DB schema)? What are the associations linking them? Can you paste the code for the dashboards? Can you paste the full exception trace?

Since we can't proceed without that information, I'm going to close this issue. I'll reopen if you provide it.
