### ISSUE TITLE
updating to 0.15.0 leads to segmentation fault

### ISSUE THREAD

**Issue by dvodvo** [thoughtbot/administrate#1954]
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
Rails 6.0.3.6

What changed?  I updated a gem version, administrate 0.14.0 to 0.15.0
When deploying to server the following error is constantly appearing. 
*Note: when reverting to version 0.14.0 the deployment process completes  (I also reporting this to the bugs.ruby-lang.org)*
 
The same occurs if I log into the server, find the current release and run `bundle exec rake assets:precompile`

Log (capistrano) attached
[capistrano_log_administrate.txt](https://github.com/thoughtbot/administrate/files/6242282/capistrano_log_administrate.txt)

**Comment by nickcharlton** [comment]
It looks like your problem here is `sassc`; Administrate doesn't include any native code so I'm not sure how it'd directly cause a seg fault.

Typically when I've had this problem it's been a case of a system library mismatch with the currently compiled version of Ruby.

I'm going to close this one (I'd recommend opening up an issue upstream) but if you can pin point it down to something in Administrate, please reopen!
