### ISSUE TITLE
Generating views creates wrong file paths

### ISSUE THREAD

**Issue by leewaa** [thoughtbot/administrate#202]
I ran `rails g administrate:views` and I got:
```
create  app/views/admin/applications/index.html.erb
...
```
The paths are wrong. It should be:
`app/views/administrate/application/index.html.erb` etc. 

The docs state the correct paths:
http://administrate-docs.herokuapp.com/customizing_page_views

**Comment by 5minpause** [comment]
I'd like to take a look at it.

**Comment by leewaa** [comment]
No no it should be `/administrate`, this is how to override the views from the gem, in any other directory you are simply adding new views and not overriding anything.

***also*** 

It is creating the views under `.../applications/...` which is totally wrong, should just be `.../application/...`.

**Comment by leewaa** [comment]
Plus keep in mind these are the base views...

**Comment by 5minpause** [comment]
@leewaa Yes, I believe you are right. I created a Pull Request for @graysonwright. The part with `applications` instead of `application` is curious. If run inside an test Rails app I can confirm your comment. When just running the Administrate tests, I get `application`. I fixed this as well in the PR. Hope this is the correct way to handle this?

**Comment by graysonwright** [comment]
@leewaa and @5minpause - thanks for the contributions!

It turns out both `app/views/admin` and `app/views/administrate` both work fine. Rails looks up views based on the inheritance tree of your controllers. In this case, our inheritance tree looks like:

```ruby
Administrate::ApplicationController
Admin::ApplicationController
Admin::CustomersController # base level
```

so Rails will look for views in:

`app/views/admin/customers`,
THEN `app/views/admin/application`,
THEN `app/views/administrate/application`.

In the future, we'd like to support multiple admin dashboards in the same application, by nesting them under different namespaces (e.g. `app/views/admin` and `app/views/super_admin`). In that case, views under `app/views/administrate` would apply to *all* of the admin dashboards. Views under `app/views/admin` would only apply to the dashboard at the `/admin` route, and wouldn't affect the dashboard at `/super_admin`.

I'm not sure that affects us now, but it might be nice to keep the views under `/admin` because changes that people make will be more contained down the line.
I think I'd prefer to keep the generated views in `app/views/admin`.

**Comment by 5minpause** [comment]
That makes sense. Thanks for clearing this up. What about the `application/applications` issue though, @graysonwright?

**Comment by graysonwright** [comment]
yeah, I think that should definitely be `app/views/application/...`.

**Comment by graysonwright** [comment]
#221 will fix this.
