### ISSUE TITLE
Something I found useful using Pundit

### ISSUE THREAD

**Issue by gpinkham** [thoughtbot/administrate#204]
wasn't sure where to include this since there aren't any Wiki pages for the project..      I use Pundit and I have some special security for some Models..  especially my audit trail which I no one should be able to edit/delete..      so I copied the _collection.html.erb file from Administrate into my app/views/administrate/application/ folder..   I then wrapped the links in calls to Pundit and bingo.. no more edit/delete buttons..   much easier then having to customize the individual pages for each resource. 

```
      <td><% if Pundit.policy(current_platform_user, resource).edit? %>
        <%= link_to(
                  t("administrate.actions.edit"),
                  [:edit, Administrate::NAMESPACE, resource],
                  class: "action-edit",
              ) %><% end %></td>

      <td><% if Pundit.policy(current_platform_user, resource).destroy? %>
        <%= link_to(
                  t("administrate.actions.destroy"),
                  [Administrate::NAMESPACE, resource],
                  class: "table__action--destroy",
                  method: :delete,
                  data: { confirm: t("administrate.actions.confirm") }
              ) %><% end %></td>
```

**Comment by graysonwright** [comment]
@gpinkham nice! Thanks for sharing.

It doesn't look like this is an actual issue, so I'm gonna go ahead and close this. I'd love to figure out how to customize the actions for a resource in a more flexible way, though (e.g. what if I want to add a "Reset Password" link to user resources?

I feel like we can figure something out so that this Pundit use case is supported. Thoughts?
