### ISSUE TITLE
Want to disable destroy option on user show page

### ISSUE THREAD

**Issue by maxwang096** [thoughtbot/administrate#2055]
* What were you trying to do?
I want to disable/hide `destroy` button on the user `index` page.
* What did you end up with (logs, or, even better, example apps are great!)?
I disabled destory option on user index page with the following code
```ruby
# app/controllers/admin/users_controller.rb

def valid_action?(name, resource = resource_class)
  %w[destroy].exclude?(name.to_s) && super
end
```
products belong to users and products are being shown on the user `show` page. The issue is that products are being shown without `destroy` option but I want to keep for it.

**Comment by nottwo** [comment]
@norioumata 

You can do that when drawing routes:

```ruby
# config/routes.rb
namespace :admin do
  resources :users, except: [:destroy]
end
```

**Comment by stephenhighemprise** [comment]
This does not seem to be working with Rails 7.1.3.2 

resources :users, except: [:destroy] # still shows Destroy 

resources :users, only: [:index, :show, :edit, :update] # still shows Destroy

**Comment by pablobm** [comment]
Thank you for your report @stephenhighemprise. I just had a look with a newly created app, running Rails 7.1.3.4 and Administrate 0.20.1. I am observing the expected behaviour.

I wonder if there's something special in your setup that makes this not behave as expected. Here are some questions that pop to mind, apologies if they feel too obvious:

- Are your limited `:users` routes under the `:admin` (or similar) namespace?
- Could the `:users` resource be listed more than once?
- If you run `bin/rails routes`, do you see any unexpected routes that may enable `admin/users#destroy`?
- Are you running any gems that may interfere with routes?

Let's see if we can get to the bottom of this.
