### ISSUE TITLE
Is there a reason permitted params is limited to `FORM_ATTRIBUTES`

### ISSUE THREAD

**Issue by tomgatzgates** [thoughtbot/administrate#207]
There has been a use case for me where I've wanted to include a hidden field but it's been rejected as it's not in the `FORM_ATTRIBUTES`. I've forked my own Administrate and have made changes specific to my use case but wondered if this was intentional or if others would find it useful. In which case I can pop it up here in a PR.

**Comment by graysonwright** [comment]
Hey, @tomgatzgates - you should be able to customize the permitted attributes list by overriding the method in your controller. For example:

```ruby
class Admin::CustomersController
  def permitted_attributes
    super + [:attribute_for_hidden_field]
  end
end
```

Let me know if that works. We can add documentation around that.

**Comment by tomgatzgates** [comment]
I overwrote it in our fork of administrate, was generally just curious.

**Comment by graysonwright** [comment]
Hey, @tomgatzgates - sorry for the confusion. You shouldn't need to fork administrate to add permitted attributes to the list.

The recommended way to add permitted attributes to, for example, the `Customer` model, is to open up `app/controllers/admin/customers_controller.rb` and add the `permitted_attributes` method from my above comment there.

This can be done entirely in your app, without needing a fork of Administrate.

Does that answer your question? Let me know if I misunderstood.

**Comment by graysonwright** [comment]
@tomgatzgates I'm going to assume you got this figured out - let me know if there's something I need to do.

**Comment by lun4i** [comment]
Currently the ApplicationController methods has been changed a bit. [resource_params](https://github.com/thoughtbot/administrate/blob/e8c812b11a02af3c15f8d6eb5dc7b3ebb1e13340/app/controllers/administrate/application_controller.rb#L121) method returns output of permitted params for other class `YourControllerDashboard` instead of `Admin::YourController`. So, `permitted_attributes` method no longer belongs to the `ApplicationController` class, and neither used in it.
Let me know if I am wrong at this point, and if I am not - what will be a new solution?
I am digging around trying to use this workaround:
```
    private
    def dashboard
      super.permitted_attributes << :image
    end
```
Cheers

**Comment by nickcharlton** [comment]
Hi @lun4i! Could I get you to open a new issue with this as this one was closed a long time ago? We'll take it from there.

**Comment by thrillyb** [comment]
FWIW, I hit this problem and added posted solution from graysonwright to my dashboard (not controller) and it's working fine
