### ISSUE TITLE
Admin JSON REST API

### ISSUE THREAD

**Issue by costa** [thoughtbot/administrate#2072]
* I would like the same admin interface would be exposed (optionally) as a JSON REST API — with the same reasonable auth options. Bonus: OpenAPI (swagger) integration.
* Adding JSON content-type handling to the (auto-generated, virtual?) controllers. Bonus: generating OpenAPI spec while doing that as well.
* Other solutions are possible but not as convenient — let's make this more powerful than `rails_admin` and `active_admin`, yeah?

**Comment by nickcharlton** [comment]
I'm going to close this as it's generally out of scope for the project and it's been quiet for a while.

**Comment by costa** [comment]
> This is something I've thought about a lot over the years but as a possible different project (I figure the core generators work we have here for building admin dashboards, especially as it's aged and become more battle-tested is a very good — and valuable — starting point to do this.)
> 
> What do you think about trying to sketch out a way of doing this? I'm thinking we could overload the output on the controllers to return JSON when requested.

Hi @nickcharlton,

I'm sorry I couldn't find the time to get back to you with anything substantial.

I'm very interested in this feature, and I think it's pretty much in line with such an "extension" to Rails might actually have. I am not sure if it's worth building anything complex, but just accepting/returning basic JSON with the same (auto-generated?) controllers looks like something simple enough. I can share my integration that needs this feature — which I don't need any auth'n in "administrate" for (which may be the only slightly complicated issue for the task) — maybe a short demo will convince you — or anyone else who'd like to help, that this feature would make a lot of sense. My app integration will be also pretty clean, of course ;)

**Comment by n-studio** [comment]
@nickcharlton If I worked on a PR for it would it be accepted?

**Comment by pablobm** [comment]
@n-studio - We cannot tell in advance if it would be accepted or not. A PR could bring issues that we didn't anticipate. I suggest that you try a proof of concept and show it to us (just as a branch or a draft PR), so that we can see in which direction this would go. If all looks good to us, you could then polish it (add specs, etc) for a complete PR that could potentially be accepted.

**Comment by benoror** [comment]
@n-studio did you end up playing around with this idea?

**Comment by n-studio** [comment]
@benoror No, I did not.

**Comment by efatsi** [comment]
In case anyone comes digging for help here, I wrote this base controller to stand up JSON API routes while still making use of Administrate dashboard and controller logic to power the CRUD actions. https://gist.github.com/efatsi/8876fc15de38a19a7c2da380bdac57a8

I'm not sure if this would make sense as something baked into the Administrate repo but I'd be happy to attempt a PR if the team thinks otherwise and this looks like a decent starting point.

**Comment by benoror** [comment]
@efatsi This is the way! A thin layer built on top of Administrate's existing APIs, customizable per your own JSON API needs (i.e. using a specific serializer). Hence, I don't feel it belongs to the core of Administrate itself, but instead up to each to develop, or maybe an Engine/Gem on top of it!

**Comment by nickcharlton** [comment]
That's a nice way of doing it!

I've been curious for a while what it would be like to be able to follow the same pattern Rails can with multiple content types, but it's not something I can look at any time soon.

I also thought about extracting the core of Administrate, and then building a new engine based on it as an API equivalent. One day.
