### ISSUE TITLE
Ability to show HasMany count on Show page

### ISSUE THREAD

**Issue by richardonrails** [thoughtbot/administrate#2192]
Assume you have a `BlogDashboard` with `articles: Field::HasMany`.

On the List Blogs page, if `articles` is included in `COLLECTION_ATTRIBUTES`, by default administrate will show a really nice feature to show the count (e.g. "231 articles").

However on the Show Blog page, you can see a Table/List of the first 5 (or whatever you set `limit` at) articles, however there's no way to see the total Article count.

**Comment by pablobm** [comment]
It should be possible by doing the following:

1. Create a method in your model that returns the article count. Eg: `def article_count; articles.count; end`
2. Create a field on the dashboard for this method. Eg: `article_count: Field::Number`.
3. Configure this field to appear on the show view instead of the original association.

One issue I'm seeing with my example is that the field will render the number with no more details (eg: "123" vs "123 articles")... You could instead use a `Field::String` and make the custom method return a string formatted as appropriate as opposed to the number.

I think that should solve your issue, so I'm going to close this. However do let us know here if there's anything else.

**Comment by richardonrails** [comment]
Thanks for the response. I understand it's possible to manually create a computed field to show the count like this.

But I thought it was somewhat inconsistent that in one place (the listing page, if you have a column for the has_many) this count automatically shows up, but then you click into the details and it doesn't. So I thought it would be a nice built-in feature of Administrate.
