### ISSUE TITLE
Adding actions to dashboard

### ISSUE THREAD

**Issue by gjackson12** [thoughtbot/administrate#222]
Is there a way to add custom actions to the dashboard view? Right now I just see edit, and destroy. Along those actions I would like to list a few other custom actions if possible.

**Comment by graysonwright** [comment]
@gjackson12 this has been on my wishlist for a long time now. :smile: 

At the moment, you need to do it all from scratch - run `rails generate administrate:views:index YourResourceName`, add a link, and add a custom controller action.

I have a few ideas in mind for how we could improve this process, but I'd love to hear your thoughts - what API would you want for this?

**Comment by gjackson12** [comment]
One other question. Let's say I added an action called "send_notification" to the Users resource. Do I need to create that route manually? 

(thinking of some suggestions for the API)

**Comment by graysonwright** [comment]
@gjackson12 yep - you'd need to create the route yourself to match your controller action.

**Comment by graysonwright** [comment]
(that's how it works at the moment)

**Comment by gjackson12** [comment]
So I added the following route: 
```
post 'admin/users/:id/send_notification', to: "admin/users#send_notification", as: 'send_notification_admin_user'
```
I also put the following in my controller: 
```
def send_notification
end
```

Finally, I have the following in the view: 

```
 <td><%= link_to(
   t("administrate.actions.send_notification"),
   [:send_notification, Administrate::NAMESPACE, resource]
 ) %></td>

I keep getting an error concerning the route not existing. Any help would be appreciated. 

```
undefined method `send_notification_admin_user_path
```

**Comment by graysonwright** [comment]
hm... I think you might need to include a `method: :post` argument in your `link_to` helper.

**Comment by ariejan** [comment]
@gjackson12 are you defining that in the `admin` namespace? Your url helper would need to be prefixed with `admin_` in that case. Check with `rake routes` if unsure.

**Comment by graysonwright** [comment]
@gjackson12 ping. Any updates here?

**Comment by johnmeehan** [comment]
Just change the order of the link_to attributes to  ` [Administrate::NAMESPACE, : send_notification, resource]`
```erb
        <td><%= link_to(
            t("administrate.actions.send_notification"),
          [Administrate::NAMESPACE, : send_notification, resource],
          method: :post
        ) %></td>
```
This will generate your link route correctly.

In my routes.rb  I added a 'clone' action by adding
```ruby
  namespace :admin do
     DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    post 'palladio_styles/:id/clone', to: "palladio_styles#clone", as: 'clone_palladio_style'

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
```

This gives me the additional route I need:
` admin_clone_palladio_style POST     /admin/palladio_styles/:id/clone(.:format)                                       admin/palladio_styles#clone`

**Comment by joaodiogocosta** [comment]
@gjackson12, this is my slightly different approach:

```ruby
namespace :admin do
  DashboardManifest::DASHBOARDS.each do |dashboard_resource|
    resources dashboard_resource do
      
      if dashboard_resource == :palladio_styles
        member do
          post :clone
        end
      end

    end
  end

  root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
end
```

Not perfect, but still, cleaner than having to write all the stuff by hand Rails' already generating for you.

**Comment by carlosramireziii** [comment]
@gjackson12 Were you able to get your custom action and link working?

There are a couple of good approaches outlined above. I'm going to close up this ticket for now.

**Comment by bo-oz** [comment]
Is there still any roadmap for Administrate? An easier API to add custom actions would be highly appreciated. I think generating the views for each model with custom actions, created unnecessary amounts of boilerplate. Would be great if there was a way to define the actions in the Dashboard or Controller class.

**Comment by vizcay** [comment]
Hi, why is this closed?  Is not a fair feature request to have in the issue tracker?

If is open someone with a bit of background may jump and do it.

**Comment by jabbett** [comment]
In my case, I wanted to update a record's status with a single click. I only needed to customize my model's `_collection.html.erb` file, since I leveraged the existing `update` controller action.

In this example, my model is `Author`, and I'm trying to change it's `status` field to `active` :

```
<%= button_to(
  "Activate",
  admin_author_path(resource),
  method: :patch,
  params: { author: { status: 'active' } }
) %>
```

I hope this helps others!

**Comment by jesseduffield** [comment]
I've been taking a look at Administrate as an alternative to RailsAdmin and it looks like the ability to easily add custom actions is the main thing that's currently missing. In rails admin you can specify actions against models and those actions will show up next to the default routes like so:

<img width="727" alt="image" src="https://github.com/user-attachments/assets/e528296a-7ef9-4562-a3a0-edc5bc22ce42" />

You can implement each action either as immediately doing something upon clicking it, or having it first show a form and then doing something upon form submission.

Actions also automatically appear at the end of tables for easy access:

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/b3af17b8-9a12-4422-aa60-1dfe0081dfbf" />

I think that actions should be considered a first-class entity in Administrate, just like they are in RailsAdmin, and I believe that Administrate can find a way to implement it that aligns with its value of using as much regular rails as possible.

I'm eager to switch over to Administrate because I much prefer its general approach to RailsAdmin but it sounds like this shortcoming is going to be too onerous to justify the switch.

**Comment by nickcharlton** [comment]
@jesseduffield, could you open a new issue, and reference this one?

I think we should revisit this, as it has significant merit, but this particular issue has a lot of solutions which are likely not relevant any more and folks who are no longer so closely involved with Administrate.

**Comment by jesseduffield** [comment]
Sure thing, see https://github.com/thoughtbot/administrate/issues/2743
