### ISSUE TITLE
TypeError in Admin::UsersController#index Admin is not a module

### ISSUE THREAD

**Issue by syafiqfaiz** [thoughtbot/administrate#225]
Hi, I am trying to install Administrate for my app, and  I got this error when accessing the admin page.

I did ```$ rails generate administrate:install```

Am I missing any step?

**Comment by graysonwright** [comment]
uh oh - looks like you have `Admin` defined somewhere else in your application - likely as a database model. Is that right?

**Comment by syafiqfaiz** [comment]
Thats true, I have an Admin model.

**Comment by graysonwright** [comment]
ah...

Right now Administrate's `admin/` namespace is hard-coded, so it'll be a bit difficult to get it working with your application. I think the best option would be renaming your `Admin` model to `AdminUser` or something similar. You can use `self.table_name = "admin"` in your model to avoid database migrations.

We're still pretty early on in Administrate's lifespan, so we'll definitely address this - it just might take a wile, since we're focusing on stability first.

**Comment by syafiqfaiz** [comment]
ok!,

thanks for the fast feedback!!

**Comment by graysonwright** [comment]
No problem! Sorry I can't help out more. /=

**Comment by Bodacious** [comment]
Would be great if you renamed the namespace to `Admins` to avoid this. Or, offer the option to customise the namespace name

Thanks!

**Comment by abradley75** [comment]
Or change it to administrate/ to avoid this :)

**Comment by nickcharlton** [comment]
FYI: This is something we're looking at in #956.
