### ISSUE TITLE
Feature Idea: Out of The Box Metrics

### ISSUE THREAD

**Issue by Chadh13** [thoughtbot/administrate#236]
Hi @graysonwright, I'd like to know if you think that this feature concept is something that belongs in Administrate or not.

#### What
Out of the Box Metrics

#### Why
- Without fail, every single one of our clients (nontechnical startup founders) has wanted metrics. 
- People rarely know what metrics are actually valuable indicators for a company early on.
- Inexperienced business people tend to use misleading vanity metrics such as totals, instead of rates of change.

Note: It is still a concept and definitely not styled.

![users cockpit 2015-11-12 17-19-41](https://cloud.githubusercontent.com/assets/2566348/11134407/0ff3ba10-8962-11e5-8cba-93e33d9c970b.png)

**Comment by graysonwright** [comment]
@Chadh13 I like the idea. In my early concepts of Administrate, I had similar metrics displayed above the index page.

I think this would be better suited for a plugin of some kind, instead of in Administrate core. We're hoping to have official plugin support in `0.1.3`, which will be released sometime in December.

I'm going to close this because there's no way to move it forward until the plugin system is in place. Feel free to add comments or re-open if it's appropriate.
