### ISSUE TITLE
Boolean field not working in example app

### ISSUE THREAD

**Issue by pablobm** [thoughtbot/administrate#2366]
Behaviour I've noticed on the demo site and reproduced locally:

1. Visit the [customers dashboard](https://administrate-demo.herokuapp.com/admin/customers).
2. Visit any customer with a NULL `email_subscriber`. These appear as a dash `-` in the index listing.
3. Click to edit.
4. Save without changing anything.

Observed result: the value of `email_subscriber` changes from NULL to `false`.

Expected result: the value of `email_subscriber` should stay NULL.

**Comment by littleforest** [comment]
@pablobm I feel like this behavior is actually correct. For a boolean checkbox, there is no way for the app to know whether you intend to leave the field as `nil` or mark it as `false`. Since it is a boolean field, I think it is okay that we assume it will be either `true` or `false`. I think the user should use `Field::Select` if they want three options for the boolean.

**Comment by pablobm** [comment]
Yeah, you may be right :thinking: My concern is that this may change data silently, without the knowledge of the admins.

For example: an app adds a "legal consent" boolean on users, but it's initially NULL to signify that the user hasn't answered the question yet. Then admins could be setting this to `false` unintentionally when they edit users.

Theoretically, this could be addressed by leaving NULLs unchanged, and only allow the transitions NULL-true, true-false, false-true... but then what if the admin actually wants to transition NULL-false.

I guess it's on the admins to know that a Boolean is not correct thing to use. It still worries me, as I think its an easy mistake to make.

Thoughts? Happy to close if you think it's indeed on the admins to know. I guess at the very least we should mention it in the documentation. But who reads that! :stuck_out_tongue:

**Comment by littleforest** [comment]
@pablobm maybe this is too complicated, but what if the boolean field defaults to a select with options [`nil`, `true`, `false`], and we could have an `allow_nil:` option on the BooleanField. If the user sets `allow_nil: false`, then it just displays the current checkbox field.

Otherwise I don't think there's really a way for a user to specify the NULL-false transition as you noted, and we would probably just have to beef up the documentation to point this out.

**Comment by pablobm** [comment]
Closing this. I think it's on admins to know, and adding it to the documentation is neither obvious nor effective (I can't imagine anyone reading it!).
