### ISSUE TITLE
Is this abandonware? 

### ISSUE THREAD

**Issue by Andrew-Max** [thoughtbot/administrate#2441]
Is there still any plan to get this to 1.0? Some major links on the main page go to 404s. Just curious before I invest time in this

**Comment by nickcharlton** [comment]
It is, unfortunately, very dependent on how I'm able to carve out time and Administrate is getting a bit of a bad time because of that at the moment. Whilst it's not just me (at thoughtbot) making contributions, I'm definitely a bottleneck to getting some stuff done.

My plan is to think about cutting a 1.0 once we've fixed the current asset handling work. We use Administrate on a bunch of internal projects and many client projects, and it's been great. 

I haven't forgotten about it, my GitHub notifications are full of everything from the last month or two, and I'm still committed to it. But ✨ time ✨.
