### ISSUE TITLE
Limit admin interface to sub-net and localhost

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#252]
Use case: Limit admin via ip address for staging and production.

Example from: http://stackoverflow.com/questions/11636228/whitelisting-list-of-ips-with-some-subnets-in-rails-3-application

    before_filter :protect

    def protect
      @ips = ['127.0.0.1', '192.168.1.0/24'] #And so on ...]
      allowed = false
      # Convert remote IP to an integer.
      bremote_ip = request.remote_ip.split('.').map(&:to_i).pack('C*').unpack('N').first
      @ips.each do |ipstring|
        ip, mask = ipstring.split '/'
        # Convert tested IP to an integer.
        bip = ip.split('.').map(&:to_i).pack('C*').unpack('N').first
        # Convert mask to an integer, and assume /32 if not specified.
        mask = mask ? mask.to_i : 32
        bmask = ((1 << mask) - 1) << (32 - mask)
        if bip & bmask == bremote_ip & bmask
          allowed = true
          break
        end
      end

      if not allowed
         render :text => "You are unauthorized"
         return
      end
    end

**Comment by graysonwright** [comment]
Hey, @ACPK! You should be able to accomplish this in your app by putting that snippet in `app/controllers/admin/application_controller.rb`. Is that working for you?

**Comment by ACPK** [comment]
@graysonwright - Yes, it works. Would love to see it out of the box though to support strong security standards since most admin area have somewhat confidential information.

**Comment by graysonwright** [comment]
@ACPK it's a good idea, but Administrate is explicitly avoiding authentication and security logic because they vary too much from app to app.

Our hope is that customizing `Admin::ApplicationController` gives you enough flexibility to implement any authentication strategy that you need in your app, without us needing to make decisions about how authentication should look for our users.

Also, I asked @danbee about this, and he pointed out https://github.com/locaweb/ip_restriction as a possible pre-built solution. Adding that to your `/admin` routes should be an easy way to get the behavior without writing a bunch of custom code.

Thanks for the suggestion! Let me know if you have questions.
