### ISSUE TITLE
Rubocop errors in arrays

### ISSUE THREAD

**Issue by Marthyn** [thoughtbot/administrate#257]
When i generate the dashboards and run rubocop i get the following errors in every dashboard file
```
app/dashboards/user_dashboard.rb:71:16: C: Avoid comma after the last item of an array.
    :onboarding,
```

**Comment by graysonwright** [comment]
Hey, @Marthyn - thanks for pointing that out.

Our generated code follow's [thoughtbot's style guide](https://github.com/thoughtbot/guides/tree/master/style/ruby), which *prefers* trailing commas.

[Here's where we discussed](https://github.com/thoughtbot/guides/pull/167) adding the trailing comma guideline to our styleguide - support was essentially unanimous.

Because of that, I don't think we're comfortable changing up the trailing comma behavior. If it doesn't work with your style config, you'll probably be stuck removing the commas manually. :disappointed: 

If it helps, [here's the setting in our Rubocop config](https://github.com/thoughtbot/hound/blob/master/config/style_guides/ruby.yml#L117-L124) that will stop Rubocop from marking that as a violation.

**Comment by Marthyn** [comment]
Ah makes perfect sense!
