### ISSUE TITLE
Submenu for less important models?

### ISSUE THREAD

**Issue by heri** [thoughtbot/administrate#261]
Hi

I am looking to use administrate for a healthcare site. There are many models, and I am looking to have a main right menu, clicking on a main model would expand on additional models. 

For example:

```
- Users
- Categories
- Services
- Conversations
- Transactions
```

When the user clicks on `conversations` then it would show :

```
- Users
- Categories
- Services
- Conversations
   * Messages
   * Bookings
- Transactions
```

Same for transactions which would then show `transactions_processes` `transitions` `shipping addresses` `payments` `checkout_accounts`, and so on. 

The benefit is to show a simpler interface when the user logs in, but still being able to have a more complex interface, if required.

Has anyone done something similar? What would be the optimal way to do this?

Thank you

**Comment by heri** [comment]
I have an array in `DashboardManifest` 
```
  MINOR = [
    :listings,
    :listing_availabilities,
    :messages,
    :locations,
    :transactions,
    :testimonials
  ]
```
and have added padding for those "minor" models (see [commit](https://github.com/heri/administrate) )
![screen shot 2015-11-21 at 2 56 35 pm](https://cloud.githubusercontent.com/assets/5634/11320245/43996e50-9060-11e5-8780-d8a1e5184b2e.png)

But still wondering if someone had done something more elegant

Thank you

**Comment by graysonwright** [comment]
Hello, Heri!

I think the best way for you to do this would be to copy [the sidebar template](https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/_sidebar.html.erb) into your host application, at `app/views/admin/application/_sidebar.html.erb`, and make the customizations in your host application instead of in your fork of Administrate.

You can also copy over [application.scss](https://github.com/thoughtbot/administrate/blob/master/app/assets/stylesheets/administrate/application.scss) into your `app/assets/stylesheets/administrate/application.scss` for custom stylesheets.

To make this process easier, I'm adding generators to copy over the files automatically. (#269)

**Comment by carlosramireziii** [comment]
@heri 

#269 has been merged so you can now generate the sidebar view with the following command

```
rails generate administrate:views:sidebar
```

See [the documentation](https://github.com/thoughtbot/administrate/blob/master/docs/customizing_page_views.md) for more information.

**Comment by neidiom** [comment]
How do we handle this issue in 2021?

**Comment by pablobm** [comment]
Nowadays, the generator is called `administrate:views:navigation`.
