### ISSUE TITLE
Snakecased routes not being properly generate on show pages of resources

### ISSUE THREAD

**Issue by brolinr** [thoughtbot/administrate#2624]
* What were you trying to do?
I've been adding routes with underscores e.g `line_item`, `business_hours`, `stock_units` e.t.c

* What did you end up with (logs, or, even better, example apps are great!)?
- The index route works fine but when I try to access the show page I get a NoMethodError as demonstrated by the image below.
- I then have to add another route `resources :stockunits, controller: 'stock_units'` and the better part is I don't get duplicated resources on the side panel.

![image](https://github.com/user-attachments/assets/e60b1c76-620c-4a05-88d0-4874882b4ab5)

* What versions are you running?
  - Rails 7
  - administrate 0.20.1

**Comment by Montana** [comment]
Hi @brolinr,

The problem could be that Rails is automatically pluralizing or singularizing the resource name incorrectly due to naming conventions, especially since you have underscores in names like `stock_units`.

Honestly I'd check the route naming. It looks like Rails is confused about the route names due to the use of underscores. 

When you declare the resource, Rails automatically generates route helper methods based on the controller name and resource name. If you declare your route as:

```ruby
resources :stockunits, controller: 'stock_units'
```
Then the path helper would be `superadmin_stockunits_path` and not `superadmin_stock_units_path`. This could be why you're facing the `NoMethodError`.

You can ensure Rails understands the resource name correctly by adjusting the resources declaration:

```ruby
resources :stock_units, controller: 'stock_units'
```
This way, Rails will generate the appropriate route helpers like `superadmin_stock_units_path` (with underscores).

Ensure that in your views (e.g., `show.html.erb`), you're using the correct route helper methods that match the resource declaration:

```erb
<%= link_to 'Show', superadmin_stock_unit_path(@stock_unit) %>
```
Finally just check the namespaces:

```ruby
namespace :superadmin do
  resources :stock_units
end
```
This should resolve the issue.

**Comment by nickcharlton** [comment]
@Montana's comment is spot on here — it seems like you're breaking Rails conventions slightly, and because we reflect on the routes (mostly) the route helpers will give you a result that's invalid.

I'm going to close this for now, but if you change them around and it's still not working, feel free to just reopen it.
