### ISSUE TITLE
[Prototype] Sort by customer orders & lifetime value don't work

### ISSUE THREAD

**Issue by swrobel** [thoughtbot/administrate#265]
https://administrate-prototype.herokuapp.com/admin/customers?direction=asc&order=orders
https://administrate-prototype.herokuapp.com/admin/customers?direction=asc&order=lifetime_value

**Comment by graysonwright** [comment]
@swrobel Thanks for pointing this out!

`lifetime_value` doesn't work because it's a computed value. I think we'd be able to support this without much difficulty.

`orders` is a `has_many` relationship, which is a bit trickier. Perhaps the behavior that makes the most sense would be to sort by the number of associated records?

**Comment by getaaron** [comment]
@graysonwright For `has_many` relationships, sorting by the number of associated records would be a pretty good default — better than what's there now.

Might be nice to offer the option to pass in a block to handle custom sorting logic like Enumerable's [sort](http://ruby-doc.org/core-2.3.1/Enumerable.html#method-i-sort) or the option to pass in a hash with options like in ActiveRecord's [order](http://apidock.com/rails/ActiveRecord/QueryMethods/order).

**Comment by pablobm** [comment]
With https://github.com/thoughtbot/administrate/pull/999, the default sorting became:

* has_many: by number of records.
* belongs_to: by record id.

I'm having a think around how we could provide custom, per-attribute sortings, but I think that falls outside the scope of this issue, so I'm closing.
