### ISSUE TITLE
Error while using Administrate when Ahoy is already installed in App

### ISSUE THREAD

**Issue by kapilpdev** [thoughtbot/administrate#2689]
* What were you trying to do?
I was trying to see the user page in the administrate dashboard and it throws me an error
i can see the index of users but when i click on a specific user it give me this error:
Ahoy is tracking every action, so whenever I try to open any model's show page this error is shown
* What did you end up with (logs, or, even better, example apps are great!)?

![Screenshot from 2024-10-24 17-13-26](https://github.com/user-attachments/assets/e22d2b2a-7aa6-404c-8522-06dacd10932f)

![Screenshot from 2024-10-24 17-10-53](https://github.com/user-attachments/assets/10feeeb8-e0cb-4f5f-a7b4-e090447e5ec5)

* What versions are you running?
  - Rails 7.2.1
  - administrate 0.20.1

**Comment by nickcharlton** [comment]
Thanks for opening this!

Could you be able to setup an example project in a repo somewhere where I can try out this particular situation? I've not used Ahoy before, so I don't know how it might be, but it seems like it's clashing somewhere.

**Comment by kapilpdev** [comment]
Hey @nickcharlton I have made this sample project with user model
https://github.com/kapilpdev/administrate-ahoy

**Comment by srbaker** [comment]
I'm sure this is because the Visit model from ahoy lives in Ahoy::Visit, and aministrate doesn't support namespaced model names (yet).

**Comment by nickcharlton** [comment]
@kapilpdev, thank you! I'll take a look soon.

@srbaker, yeah, that's likely it. It _does_ support a lot more than it did, but we might have just found a situation where it's not working.

**Comment by nickcharlton** [comment]
Sorry this took me ages. I've been trying to get everything ready for v1, and I knew this would take a bit of time to dig into. Thanks for the example application, I tried that out, and it really helped me understand how it's breaking.

I tried with `0.20.1`, as you'd set up with, and also `1.0.0.beta2` (I was curious if it was indeed just a namespacing issue we might've fixed). It's not, though, and is actually a good opportunity to build a custom field type.

It's breaking because Administrate expects a `belongs_to` field to have a dashboard to go with it. You can generate one with: `rails g administrate:dashboard Ahoy::Visit`.

You may also have to do something like this (I tried this first before realising):

```
ATTRIBUTE_TYPES = {
    id: Field::Number,
    ahoy_visit: Field::BelongsTo.with_options(class_name: "Ahoy::Visit"),
}
```

I was able to get it to render a dashboard that looks like this:

<img width="1303" alt="Screenshot 2024-11-25 at 12 46 48" src="https://github.com/user-attachments/assets/4ac4ddf7-fa5d-471e-91a4-dbcef623d1f1">

I presume that's not actually helpful though, what would you expect a field like this to show?

**Comment by kapilpdev** [comment]
@nickcharlton Naturally Ahoy visits generate automatically as it stores the activities of a user. Each new visit stores data such as: the user navigated from one page to another in the application, the user clicked a button, or the user created a new object.

So in my project I was not able to create a Dashboard for the Ahoy Visits, and because of the same reason I had to remove all the ahoy visit references from all the dashboard of the models it was associated to.

**Comment by nickcharlton** [comment]
I think that's the behaviour I would expect. You'd need to make a custom field, or perhaps even a dashboard, as a way to take the Ahoy visits and make them useful to you.

It's not something Administrate would do, but I'd recommend exploring how you can extend it to do so and feel free to open more issues if there's specific hooks Administrate could expose to make it possible.
