### ISSUE TITLE
Rails 8.0 support

### ISSUE THREAD

**Issue by bzq360** [thoughtbot/administrate#2703]
Hi, 
[Rails 8.0.0](https://rubygems.org/gems/rails/versions/8.0.0) has just been released yesterday (Nov 7th, 2024). I can see the `administrate.gemspec` has limited the ActiveRecord dependency to below 8.0 in December 2023. So, when I run `bundle install` with **Administrate 1.0.0-beta2** and **Rails 8.0**, I get a `Could not find compatible versions` error.

Can I ask when **Rails 8.0** will be supported please?

<img width="969" alt="image" src="https://github.com/user-attachments/assets/a267a18a-b342-478a-a573-7a4bb76b97c4">

<img width="564" alt="image" src="https://github.com/user-attachments/assets/69751573-11ff-4db4-91bd-a7822eea1d03">

**Comment by nickcharlton** [comment]
Thanks for opening this! We can use this issue for tracking incompatibilities, if there are any.

We originally restricted to the current latest version to try and avoid people having a bad time when they upgrade, but it does mean we need to do a bit of work when new major Rails versions are released.

I plan to start on a PR today to open up the dependency restriction, then we can test that out and see what, if anything, breaks. I'd expect it to go out in the next beta release of v1.0.0, as it's big enough to avoid an rc just yet.

**Comment by nickcharlton** [comment]
I started on this, and so far we're waiting on `rails-i18n` support: https://github.com/svenfuchs/rails-i18n/pull/1130

**Comment by nickcharlton** [comment]
I've been working on getting CI running now with Rails 8.0 added, which is still ongoing. Aside from CI, Administrate seems to be able to be installed correctly on Rails 8.0, assuming you're using Sprockets.

I've since opened #2709 though, as it doesn't work with Propshaft because Administrate assumes it's there.

Another fun thing that I've noticed: we added the upper Rails constrain on installing between 0.19.0 and 0.20.0, so if you install Administrate on a new Rails 8.0 app, you're going to get version 0.19.0.
