### ISSUE TITLE
Raise error for incorrect use of `Field::` namespace for custom fields

### ISSUE THREAD

**Issue by Rodrigora** [thoughtbot/administrate#280]
Hi all,

after creating a custom field using this command:

```
rails generate administrate:field belongs_to_with_blank_option
```

I started to get this error only in production environment while initializing the app:

```
uninitialized constant Administrate::Field::BelongsToWithBlankOptionField (NameError)
```

Any ideia?

**Comment by graysonwright** [comment]
@Rodrigora Can you paste the contents of the Dashboard class that's using the `BelongsToWithBlankOption` field? I suspect that you're using:

```ruby
Field::BelongsToWithBlankOptionField
```

when you should be using:

```ruby
BelongsToWithBlankOptionField
```

**Comment by Rodrigora** [comment]
@graysonwright you're right!!

Thanks a lot! :+1:  

But i'm a little confused on why it worked on development

**Comment by nextekcarl** [comment]
I'm adding this note because this fixed a problem I was having where using Field::CloudinaryField (the custom field I added) was working just fine in development and staging, until I used it on a second model. Then I started getting fairly random uninitialized constant Administrate::Field::CloudinaryField (NameError) errors. About 1 in 5 reloads would work in development; the rest had that error. But once I made the change mentioned in this ticket it reliable worked in development and production. I think adding something about that to the docs might help other people. I thought I saw the Field::CustomField style in the docs, but just checked and don't see it, so it must have just been me following the style for the other (pregenerated) dashboard field entries.

**Comment by graysonwright** [comment]
@nextekcarl you're right, this seems to be something that's throwing a lot of people off. Documentation could definitely be improved here.

I'm really curious about why this is working sporadically in development - it seems like it should just fail outright. I'll try to investigate a bit on this.

**Comment by nextekcarl** [comment]
I wonder if it depends upon the initialize order? I'm not sure how that's
handled, but it it isn't a determinate order maybe?

**Comment by avk** [comment]
I just made this same mistake @nextekcarl. What's the status on updating the documentation? Happy to try if it hasn't been done.

**Comment by carlosramireziii** [comment]
@avk AFAIK there hasn't been any updates to the documentation or code to raise an error on this. 

If you'd like to tackle it, that'd be great!

Perhaps update [this document](https://github.com/thoughtbot/administrate/blob/master/docs/adding_custom_field_types.md). A code snippet on the usage of the custom field could be helpful, and there you could show that it should be (for example) `GravatarField ` not `Field::GravatarField`. 

LMK if you're up for it. Thanks!

**Comment by ndrluis** [comment]
I think that the documentation is up to date and this issue could be closed.

**Comment by nickcharlton** [comment]
@ndrluis Thanks! Gonna close this.
