### ISSUE TITLE
Set ruby version for CircleCI

### ISSUE THREAD

**Issue by calrrox** [thoughtbot/administrate#289]
Hi, excuse me for return to discuss this.

On the issue #253 it was concluded that it was not necessary to add to "circle.yml" the version of ruby.

But I think so, because the ".ruby-version" file is used by "RVM" to declare "gemset" for example, and the name of this "gemset" is user preference.

So I think it is best set to "circle.yml" version of ruby and add to ".gitignore" the file ".ruby version" like another projects.

**Comment by graysonwright** [comment]
I took a look at:

- <https://github.com/rails/rails>
- <https://github.com/sferik/rails_admin>
- <https://github.com/activeadmin/activeamin>

and they all have `.ruby-version` in their `.gitignore`. It seems that the best practice in this case is to ignore the `.ruby-version` file, and let the developer customize that.

Perhaps we can generate a default `.ruby-version` file through our `bin/setup` script, which would make the process transparent for anyone using thoughtbot's dotfiles for getting set up. That may also have the benefit of keeping the CI build going with no other changes. Since the `bin/setup` script is run on CI before the build, CircleCI may recognize the `.ruby-version` file and use the correct Ruby.

**Comment by graysonwright** [comment]
This is now being discussed on #299. I'll close this so we can keep the conversation on that thread.
