### ISSUE TITLE
Hierarchy and custom fields

### ISSUE THREAD

**Issue by masciugo** [thoughtbot/administrate#300]
I'd like to create a custom field inheriting from `Administrate::Field::HasMany`. Where can I set the options? For example to increase the number of items to show for an HasMany like field I tried the following without success:

```
class HasManyPicturesField < Administrate::Field::HasMany
      DEFAULT_LIMIT = 100
end
```

My workaround was:

```
class HasManyPicturesField < Administrate::Field::HasMany
    def options
       super.merge({limit: 100})
    end
end
```

Also I expected not to be forced to create views when using inheritance. Instead I had to copy original HasMany views in my HasManyPicturesField ones. Maybe there is a better way I was not able to find.

By the way, thanks for this lib!

**Comment by graysonwright** [comment]
@masciugo thanks for bringing this up.

I was a bit surprised that the `DEFAULT_LIMIT = 100` approach doesn't work. After looking into it, it turns out that Ruby's inheritance doesn't work the same way for constants as it does for methods.

At the moment, you're doing everything the right way. It would be nice to improve the workflow in a couple ways, by letting people overwrite the default attributes, and by not requiring people to copy over templates.

I think this is low priority at the moment - it sounds like you've worked your way around both problems. This may be a good fit for our "Extensibility" milestone, so I'll add it to that.

Let me know if you have suggestions for how this can be improved!

**Comment by carlosramireziii** [comment]
@masciugo Re: view inheritance - 

I was able to achieve this by overriding the `to_partial_path` on my custom field and just telling it to use the partials from the parent field. It may be nice to add some documentation and/or make that work by default, however I thought you should know. See [here](https://github.com/thoughtbot/administrate/issues/131#issuecomment-283523064) for an example. 

Would adding some documentation regarding that be sufficient to solve you problem? If not, what's the desired behavior you'd like to see.

**Comment by nickcharlton** [comment]
I'm going to close this issue as we've go a few good solutions here. I'd love to see this in the docs somewhere, though!
