### ISSUE TITLE
Alias _requested_resource to appropriately named model

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/administrate#318]
I'd like to see the `assigns['_requested_resource']` aliased as the named model, i.e. `assigns['user']`

If we know the model type for the dashboard, this seem like a no brainer. Is there a design reason why this was not implemented?

**Comment by graysonwright** [comment]
@coneybeare, a quick note on usage:

`assigns['_requested_resource']` is a private variable used for memoization, and we don't expect you to use it. It's possible that it will change in future versions, so you shouldn't rely on it. Instead, in the `show`, `edit`, and `new` views, you can use `page.resource` to get the resource.

- - -

As for aliasing to the name of the model, we used to do that exact thing. [Here's the commit where we removed it](https://github.com/thoughtbot/administrate/commit/02290d3d). The `instance_variable_set` and `instance_variable_get` methods were responsible for doing the aliasing.

The main drive of that commit was a change from setting instance variables in the controller to passing the variables directly as local vars. There are more details in the commit message.

We removed the variable alias as a secondary change, because we weren't using it anywhere. Can you describe the motivation for the alias? Is it to make it clearer when you're overwriting views?

I can see us adding this feature back in, but I want to make sure I understand how it'll be used. I'll likely want to add documentation to go along with it.

**Comment by coneybeare** [comment]
I am sure others have other reasons to use it, but for me right now it's for controller specs. 

````
before(:each) do
  @user = FactoryGirl.create(:user)
  get :show, id: @user
end
    
it { should respond_with 200 }
it { should render_template(:show) }
    
it "assigns the correct resource" do
    expect(assigns(:user)).to eq(@user)
end
````

According to my `puts` statement in this test, the only assigns I have are `_resource_resolver`,
`_dashboard`, and `_requested_resource`.

**Comment by graysonwright** [comment]
Since we're passing variables to views in a non-standard way, I wrote a helper function that can be used in place of `assigns`. I'm using it now in an internal controller spec:

- [Helper method](https://github.com/thoughtbot/administrate/blob/master/spec/controllers/admin/customers_controller_spec.rb#L180-L191)
- [Usage](https://github.com/thoughtbot/administrate/blob/master/spec/controllers/admin/customers_controller_spec.rb#L8-L9)

It's a little bit messy, and I'm open to alternatives for testing local variables. But is that something that would work for your tests?

**Comment by coneybeare** [comment]
Indeed this will work

**Comment by graysonwright** [comment]
Based on discussion in #320, I think the local variable approach might have some drawbacks to look at. We need to make sure it's easy to override the variables passed to the views.

I'll close this issue for now and leave #320 open. If anyone has thoughts, feel free to reopen this or comment on #320.
