### ISSUE TITLE
Routes without namespace

### ISSUE THREAD

**Issue by sivicencio** [thoughtbot/administrate#405]
Is there a way to use no namespace at all? Couldn't find documentation related to this. For example, ActiveAdmin let you set `config.default_namespace = false` if you don't want to use a namespace for admin routes, so they are mounted at "root" namespace (if `Foo` is a resource, then the corresponding index is `/foo`, not `/admin/foo`)

Thanks.

**Comment by Shwetakale** [comment]
@sivicencio Currently namespace ```admin``` is hardcoded in all generators so what you are trying to achieve is not possible and we also can't change namespace.

@graysonwright Would like to take namespace from config option let me know your opinion on this.

I will send PR if you think it's useful.

**Comment by sivicencio** [comment]
@Shwetakale I was looking at the commits (after v0.1.2 release) and I saw that now the namespace is evaluated dynamically from the URL, but it assumes, though, the gem routes are mounted inside a namespace.

Also, namespace is basically used for generating resource URLs. Maybe a helper method that evaluates the presence of a namespace and generates an URL based on that would allow the ability to leave namespace as an optional parameter.

**Comment by aguynamedben** [comment]
Similar to https://github.com/thoughtbot/administrate/issues/374

**Comment by pablobm** [comment]
I've been looking into this one today. Currently, the root of the problem lies at `Administrate::ResourceResolver`. This class guesses the name/class of a given dashboard/resource based on the path of the controller. It assumes the controller is always going to be namespaced, so for "foo/bar" it assumes that the namespace is "foo" and the resource "bar".

I think this issue is legitimate, and I'd like to solve it. I've been looking into options, and I can think of two:

1. Making the resolver more clever. Eg: got `one/two/threes`? Try if the class `Foo::Two::Three` exists. If yes, no namespace. If not, try again with `Two::Three`. If it exists, namespace is `Foo`, model is `Two::Three`. Continue recursively if not.
2. Add a setting to Administrate where we can explicitly say what the namespace is, and go with that.

Quick thoughts on each:

1. I was able to implement this one today. It would look like this https://github.com/thoughtbot/administrate/commit/6162b7ecf8acbff5f3feb372b5e1fddb4bc89b75 However I fear it might be too clever by half, and have unintended side effects.

2. At the moment, we don't have any configuration system in the gem (aside from that of individual dashboards). What would this look like? What would be the limitations? I think it should be flexible enough for some dashboards living in a namespace while others aren't.

Thoughts?

**Comment by pablobm** [comment]
Actually... I thought of another way of doing this, hopefully better and more flexible.

I feel that what `ResourceResolver` is doing is already a bit too clever. It's getting the controller path and figuring things out from there. I wonder why it has to be the path, and not just the controller itself.

So instead of this:

```ruby
def resource_resolver
  @resource_resolver ||=
    Administrate::ResourceResolver.new(controller_path)
end
```

Why not this?

```ruby
def resource_resolver
  @resource_resolver ||=
    Administrate::ResourceResolver.new(self)
end
```

I think that this would allow the resolver to figure things out with less magic. Additionally, it opens the door to customisation of individual controllers. For example, we can have:

```ruby
module Admin
  class ProductsController < Admin::ApplicationController
    self.resource_class = Doohickey
    self.dashboard_class = MerchandiseDashboard
  end
end
```

This is similar to how you tell ActiveRecord to use a different table name for your models, for example. I think this would free us from having to worry about not just namespaces, but any other details that at the moment are inferred from the controller name.

If anyone wants to give this a go and provide a PR, I'll be happy to provide guidance and review :-)

**Comment by nickcharlton** [comment]
I'm going to close this as I don't think it's valuable in the short-term and in the time since the issue was opened we don't have a concrete solution to it.
