### ISSUE TITLE
Modify show template for a given field type for a given model

### ISSUE THREAD

**Issue by jeffreyguenther** [thoughtbot/administrate#439]
Is it possible to provide a template only for a particular view for a particular type?
For example, I might want to modify the DateTime type on the Show page of Person.

**Comment by graysonwright** [comment]
@jrguenther At the moment, the best way to do this is by [adding a custom field type](https://administrate-prototype.herokuapp.com/adding_custom_field_types). You can customize the `show`  partial for the field type, and copy the `edit` and `index` partials from [the built-in DateTime partial](https://github.com/thoughtbot/administrate/tree/master/app/views/fields/date_time).

In the future, I'm hoping to add a `Partial` data type that lets the user define one-off partials instead of creating entirely new field types.

**Comment by purinkle** [comment]
@jeffreyguenther, is this still an issue for you?

**Comment by jeffreyguenther** [comment]
Haven't used administrate in a couple year... so no it's not currently an issue for me.
