### ISSUE TITLE
line break in textarea

### ISSUE THREAD

**Issue by knopfler81** [thoughtbot/administrate#444]
I am using this great gem for a diary web site!
When the user write in a text area. It doesn't consider the line breaks ?
Maybe I missed something...

Thanks :)

**Comment by andrewhamon** [comment]
Are you using the `Field::Text` field type instead of `Field::String`?

```ruby
class MilkDashboard < Administrate::BaseDashboard

  ATTRIBUTE_TYPES = [
    # Other fields here
    description: Field::Text
  ]
end
```

You can try it yourself [on the demo dashboard](https://administrate-prototype.herokuapp.com/admin/products/new).

Bear in mind that if the generator created a `Field::String` field for you, then you might be using a `String` field in your database, which often means a limit of 256 characters. [This Stack Overflow question](http://stackoverflow.com/questions/3354330/difference-between-string-and-text-in-rails) gives a pretty good overview.



Generated form for `Field::Text`:

<img width="662" alt="screen shot 2016-01-30 at 10 55 34 am" src="https://cloud.githubusercontent.com/assets/5134584/12696741/39e1f744-c740-11e5-9cb2-b3ab12ec8a37.png">

Linebreaks preserved after save:
<img width="412" alt="screen shot 2016-01-30 at 10 55 55 am" src="https://cloud.githubusercontent.com/assets/5134584/12696742/3c54b08e-c740-11e5-8a33-fcc5e75e0852.png">

**Comment by knopfler81** [comment]
Hello Tanks for answering :)
line breaks appear in administrate but once online...
it just does’t display in the view with the line break….

regards

Nelly

Nelly Duclos

**Comment by andrewhamon** [comment]
That is probably because in HTML, whitespace is insignificant. So any amount of whitespace (regardless of whether it is a space or a newline or a tab) is rendered as a single space.

If you want to preserve the newlines in your own views, take a look at [this stack overflow answer](http://stackoverflow.com/a/3145798/2469769).

This is pretty clearly not an issue related to Administrate, so it would be best if you closed the issue (I can't myself as I'm not a contributor) and, if you require further assistance, look for help in a more appropriate location.

Hope I could help! :)

**Comment by knopfler81** [comment]
oh okay sorry i will close it right now!
Thanks for helping :)

Nelly Duclos
