### ISSUE TITLE
Custom TABLE_ATTRIBUTES in Dashboard

### ISSUE THREAD

**Issue by mcifani** [thoughtbot/administrate#461]
How does one create a custom Table_attribute for a dashboard?

TABLE_ATTRIBUTES = [:custom_attribute]

where can I define it?

Thanks!

**Comment by graysonwright** [comment]
@mcifani - you should be able to add the custom attribute in your dashboard class, in the `TABLE_ATTRIBUTES` array like you showed. You need to make sure you also place it in the `ATTRIBUTE_TYPES` array, so Administrate knows how to show it on the pages.

Does that answer your question? I think I'll need more information to help you out further.

**Comment by carlosramireziii** [comment]
@mcifani Just wanted to check in on this. Were you able to add your custom attribute to the table as shown above?

FYI - I believe the API has changed and instead of `TABLE_ATTRIBUTES` it's now `COLLECTION_ATTRIBUTES` ([see here](https://github.com/thoughtbot/administrate/pull/112)). 

It still works the same, however. Just add your attribute to the `COLLECTION_ATTRIBUTES` array and make sure it's defined under `ATTRIBUTE_TYPES`. 

Let me know if this solves your issue.
