### ISSUE TITLE
NoMethodError is silently ignored

### ISSUE THREAD

**Issue by naps62** [thoughtbot/administrate#480]
Following a previous issue, I added a custom field to my model:

``` ruby
class CurrencyCard < ActiveRecord::Base
  def value
    Money.from_amout(available, currency)
  end
end
```

The above code has a typo. the method's name should be `from_amount` and not `from_amout`.
But the gem is swallowing the error in this rescue: https://github.com/thoughtbot/administrate/commit/351f80ba9668fa59d2d69208a8071b89f428d63f#diff-1524c94a187c1ab4bf8c2aeceebbbc35R25

I get a `NoMethodError` exception, which is a descendant of `NameError.`
So instead of the actual error, I get a `private method 'format' called for nil:NilClass`, because an unexpected `nil` ended up in the view

The commit I referenced adds this to deal with polymorphic associations.
I couldn't find any tests dealing with that particular `rescue`, so I'm not having a lot of luck in fixing this myself

**Comment by graysonwright** [comment]
@naps62, thanks for reporting this.

Looking back on that commit you referenced, it seems like we shouldn't have that rescue in our code. We added it to take care of a bug that was showing up in Upcase.

If the database contains polymorphic associations, where some of the records have dangling references to a class that's been removed, we opted to silently assume a value of `nil` instead of letting Rails raise an error.

Looking back on it, we shouldn't stop that error from surfacing. It's a data integrity problem with the host application, and we should help surface that so users can take care of it quickly.

I'm in favor of removing the `rescue` statement.
