### ISSUE TITLE
Rails 5 compatibility 

### ISSUE THREAD

**Issue by chevinbrown** [thoughtbot/administrate#538]
Will there be a rails 5 branch released?

**Comment by BenMorganIO** [comment]
@chevinbrown I'm currently working on this in branch: https://github.com/BenMorganIO/administrate/tree/rails-5-support. Right now, I'm cherry picking commits out and submitting the PRs individually. This way its not a big bang PR.

If you would like to contribute to getting Administrate Rails 5 ready, you can totally fork my branch and submit PRs to my branch; which hopefully be fully merged later on. Or, you can make your own tiny changes and I'll rebase my branch against your changes.

**Comment by cadizjavier** [comment]
Any update on this ?

**Comment by archonic** [comment]
@cadizjavier Until there's official Rails 5 support, you can install Ben's branch with this:

`gem 'administrate', github: 'BenMorganIO/administrate', branch: 'rails-5-support'`

However, I'm getting `Attempting to generate a URL from non-sanitized request parameters!` when visiting /admin. That appears to be an [incompatibility between kaminari and Rails 5](https://github.com/amatsuda/kaminari/issues/759) which is fixed in kaminari 0-17-stable. Adding `gem 'kaminari', github: 'amatsuda/kaminari', branch: '0-17-stable'` to my Gemfile updates to that version but doesn't resolve the issue. Any ideas @BenMorganIO?

**Comment by BenMorganIO** [comment]
@archonic I'm :-1: on my branch. You should check out https://github.com/thoughtbot/administrate/pull/575 by @imajes which is much nicer than mine.

**Comment by archonic** [comment]
Thanks, that works 👍. Haven't battle tested it but so far so good.

**Comment by BenMorganIO** [comment]
Cool. Thanks @archonic. Leave a comment in #575 if you notice any undocumented issues in that discussion.

**Comment by nickcharlton** [comment]
Closing as we now have Rails 5 support in `0.3.0`, but please open new issues if we've missed something!
