### ISSUE TITLE
Resource update changes name on edit title and show resource button

### ISSUE THREAD

**Issue by alvaroemmanuel** [thoughtbot/administrate#545]
Hi,

I choose to show the title of my current item in the `display_resource(item)` method of my Items dashboard.

I also has a validator of uniqueness for the item title.

It works fine and shows the item name in the title of all the actions related to items, however, for the edit action, if say, I edit the resource and try to change the title to something that already exists, the error flash is correctly displayed but both, the edit title and the show resource button display the new introduced value instead of the actual value of the resource being edited.

For example, suppose I have 2 items in DB, with titles `item_1` and `item_2`.
If I go and edit `item_2`, the page title is "Edit item_2" and in the right side is a button that says "Show item_2".
Now, if I try to change its title to `item_1`, then an error is displayed saying the title is already taken, but the page title now shows "Edit item_1" and the button shows "Show item_1", which is incorrect, since I'm editing `item_2`.

**Comment by pablobm** [comment]
Hi @alvaroemmanuel - It's been a long time, apologies.

This is a typical issue with Rails. It's easy to reproduce if you create an admin panel yourself, for example with a scaffold.

A way to avoid it is to implement that method as follows:

```ruby
def display_resource(product)
  product.name_was
end
```

Note that this uses a `*_was` method from [ActiveModel::Dirty](https://api.rubyonrails.org/classes/ActiveModel/Dirty.html). This will return the value as persisted in the DB, instead of as it exists in memory. This will prevent the issue you are having.

I think it's better to do this than to have Administrate do anything magic to avoid it. It's more flexible and allows users to do more things, always using Rails's own APIs.

I hope this is helpful.
