### ISSUE TITLE
Custom Forms

### ISSUE THREAD

**Issue by kyprifog** [thoughtbot/administrate#547]
Greetings!  I really like what you guys have done here.  However, I am finding a little bit of difficulty with the docs which don't go into great detail about how to customize the form aside from simply proividing the generator for the form.  I started digging around in the generated form with page.attributes in order to attempt to filter out a specific attribute from the form that was erroring, but it was erroring in such a way that path.attributes could not be called, which makes it hard to filter out certain attributes in the form.  Our system has rather complex demands so I dont expect everything to work out of the box, but I was hoping it would be easier to customize the form.

One thing active admin did have going for it, was that its syntax for specifying custom forms was really sharp and easy to use (although active admin honestly has its own plethora of problems which I wont go into :) )

http://activeadmin.info/docs/5-forms.html

Another thing I liked about ActiveAdmin was that it was easy to build a seperate (perhaps more robust) authentication path for the administrative users.  How hard would it be to achieve this using administrate?

Thanks for the great work, this is really impressive!

**Comment by kyprifog** [comment]
Hey guys, thanks for your work on this.  I think right now I am leaning towards stepping back to using active admin but I really like what you guys have started here!

Thanks!

**Comment by BenMorganIO** [comment]
@kyprifog thanks for giving administrate a shot! I'm totally interested in the forms issue you're experiencing.

You mention that you were "digging around in the generated form with page.attributes in order to attempt to filter out a specific attribute from the form that was erroring". Its a bit of a run on sentence and I'm having a hard time grasping it. Can you please elaborate on this?

 What would you like to see in Administrate for custom forms? Perhaps I could get a PR ready :)

**Comment by kyprifog** [comment]
Hi @BenMorganIO.  I generated the form, but then found that I needed to filter out a particular attribute from being displayed on the form because it was throwing errors (which I didn't think needed to be dealt with because they were attributes that did not need to be modifying via the admin anyway).  

However, I couldn't find a systematic way of filtering particular attributes from the form in any examples so I moved back to active admin where I can whitelist the form attributes easily:

```
  form do |f|
    f.input :name
    f.input :email
    f.input :title
  end
```

**Comment by kyprifog** [comment]
Any additional thoughts here?  Otherwise I'll go ahead and close.

**Comment by BenMorganIO** [comment]
@kyprifog I usually just remove the field from the `FORM_ATTRIBUTES`. Did that not help? :/

**Comment by halfghaninne** [comment]
@BenMorganIO I'm very curious about this as well, beyond temporarily removing the field. For instance, I have a drop-down field in the form for one of my resources that I would like to default to a certain value depending on the value `current_user`. Can I do this kind of customization in the `FORM_ATTRIBUTES` section of the model's dashboard?

Thanks in advance.

**Comment by carlosramireziii** [comment]
@kyprifog Just checking in on this...

What @BenMorganIO mentioned above sounds spot on to me. `FORM_ATTRIBUTES` is basically a whitelist of attributes which will show up on a generated form, similar to the functionality you are familiar with in Active Admin. I believe this is what you are looking for. Were you able to try this out? Did it solve your problem? Let us know!

--- 

@halfghaninne Would love to hear more about your use case for having a default value for a select / drop-down field. If you'd like, please go ahead and open up a new issue (if one doesn't exist) and describe your use case, the expected behavior, how you'd like it to work, etc. That'll be a good way to kick off a discussion and potentially get it implemented. Thanks!

**Comment by kyprifog** [comment]
@carlosramireziii Its been a while sorry I did not update sooner. Unfortunately for ease of use I dropped back to use ActiveAdmin for that particular project.  Thanks for your feedback though.

**Comment by carlosramireziii** [comment]
@kyprifog No worries, thanks very much for getting back to me!
