### ISSUE TITLE
Can you choose when a list appears as a normal dropdown vs a searchable one?

### ISSUE THREAD

**Issue by kieraneglin** [thoughtbot/administrate#585]
I have a long list of `locations`.  I'm going to be bulk-adding data for a while, so I'd like to have a searchable dropdown instead of a normal one.

Eg, turn [this ](http://puu.sh/oUHXz/b04fa742e9.png) into [this](http://puu.sh/oUI52/8e200aab27.png).  I tried adding `searchable: true` as an option, but that didn't work.

Both are one-many relationships.

**Comment by miksago** [comment]
I'm thinking of just doing up a plugin for this; not sure yet.

**Comment by miksago** [comment]
I copied the template and added a javascript include that was the contents:

```
$(function(){
  $('.field-unit--belongs-to select').selectize();
});
```

**Comment by carlosramireziii** [comment]
Hey @ThisIsMissEm! 

I think you've got the right idea-- a custom field is the way to go if you want to have special handling for really long lists. If you would like to package up your solution as a plugin, that'd be great!

It seems like you got this taken care of so I'm going to close this issue. Thanks!

**Comment by ThisIsMissEm** [comment]
@carlosramireziii actually, this is a bug; See https://github.com/thoughtbot/administrate/blob/master/lib/administrate/field/select.rb#L6-L8 — that value "searchable?" doesn't actually do anything in the view: https://github.com/thoughtbot/administrate/blob/master/app/views/fields/select/_form.html.erb

(granted, I suspect this could be a language thing, as what you mean by `searchable?` upon re-reading is that the Collection on the index page can be searched / filtered by that field, rather than that field is able to be searched with autocomplete)

It'd be a pretty small change to core to actually support this like you do with HasMany fields. The reason I needed this is because I was building an administration panel for a microservice, and the data for that value "locations" actually came from an upstream API call — So I had like a "Artists Adminstration panel" and a "Locations API Service", and I wanted to connect the two.

I feel like this is a pretty common use case as Microservices catch on with Rails API now being really solid.

**Comment by carlosramireziii** [comment]
@ThisIsMissEm Ah okay, tell me if I'm understanding correctly... You'd like to have the same "searchable" behavior that's implemented for `HasMany` fields using the `selectize` plugin to be possible for `BelongsTo` fields as well? 

If so, does the [`administrate-field-belongs_to_search`](https://github.com/fishbrain/administrate-field-belongs_to_search) plugin implement what you're looking for?

We can definitely open the floor to discussing whether or not the functionality belongs in a plugin, a custom subclass, or in the gem proper, but I want to make sure we're on the same page first. Let me know!

**Comment by ThisIsMissEm** [comment]
@carlosramireziii this was for the select field type

**Comment by ThisIsMissEm** [comment]
Due to being microservices based, BelongsTo isn't a database relation, but just a normal column on the table. Then the data for the admin here comes from an external service

**Comment by carlosramireziii** [comment]
Got it! 

Would you like to try your hand at a pull request or custom plugin which implements the behavior you are looking for? If the use case is common, then the community will definitely benefit from the work you put in to implementing it. Perhaps you can use the plugin which works on `BelongsTo` as a template? 

Link the PR or plugin here and I'd be happy to take a look and give some feedback. WDYT?

**Comment by ThisIsMissEm** [comment]
Hi Carlos, 

This would be an extremely low priority for me now, I actually don't use Administrate anymore (I changed jobs)

– Emelia

**Comment by carlosramireziii** [comment]
Ah gotcha. Well thank you for your feedback!

**Comment by G-Rath** [comment]
It looks like administrate has ended up taking the inverse path, by making this sort of list the default: https://github.com/thoughtbot/administrate/pull/1566

I personally think this should be provided via a plugin so that it's opt-in, as that's easier than trying to opt-out without breaking other uses of Selectize in apps (which is the situation I'm in now - alternatively I'd have to do a lot of work to try and get the selects styled like the rest of the app as they were before Selectize, which is not something I'm wanting to do when we're upgrading so we can patch Rails).
