### ISSUE TITLE
Is it possible to display an association on a particular dashboard?

### ISSUE THREAD

**Issue by davidalejandroaguilar** [thoughtbot/administrate#609]
Trying to have Order Items display the Email of the user.

`OrderItem belongs to Order belongs to User`

Already put the corresponding field, but don't know how to display the association.

Example: [http://www.evernote.com/shard/s508/sh/4a3326a6-ed93-41c2-94cf-6a4706dfe5cb/243eb98c71db1e876c5da72606a1014b](url)

**Comment by j-dexx** [comment]
You _may_ be able to do

```
class OrderItem
  belongs_to :order
  has_one :user, through: :order

  delegate :email, to: :user, allow_nil: true
end
```

Then add email to both attribute types and collection attributes in your dashboard.

```
class OrderItemDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    email: Field::String
  }

  COLLECTION_ATTRIBUTES = [
    :email
  ]
end
```

You'd probably want to amend the controller to eagerload users too

**Comment by guiloyins** [comment]
This approach breaks the in built search functionality as it will look for email column in OrderItem and will not find it.

```ActionView::Template::Error (PG::UndefinedColumn: ERROR:  column "email" does not exist```

**Comment by j-dexx** [comment]
@guiloyins You can create a custom field for it, then pass the option of searchable false.  Then it won't be included in the search.

I do not think there is an easy way to incorporate it into the search.  If you want to include it in the search you would have to create your own search and override the controller so it uses your search functionality rather than `Administrate::Search`

**Comment by purinkle** [comment]
@davidalejandroaguilar, is this issue still relevant to you?

**Comment by davidalejandroaguilar** [comment]
Not anymore @purinkle, thank you for asking
