### ISSUE TITLE
Question: default_scoped models

### ISSUE THREAD

**Issue by michaelkl** [thoughtbot/administrate#643]
Hi,

In my current project I got **Publication** model, which represents some kind of articles. Articles are required to be accepted by administrator and so the have a `published` attribute which is `false` by default.

**Publication** model has `default_scope { where published: true }`. It allows me to make all kinds of queryes in userspace in very convenient way.

But when it comes to **Publications** dashboard, things are getting worse: administrator can't see unpublished articles too!

So, as I'm new to Administrate project, my questions are:
1. Is there any way to deal with this problem?
2. What do you think about patching `Administration::Search` class to `unscope` resource before querying  it? Is it ideologically correct? Should I make a pull request?

**Comment by j-dexx** [comment]
For 1 you can go into your admin folder in the controller and override the `index` and `find_resource` methods

e.g.

```
def index                                                                 
   super                                                                   
  @resources = Publication.unscoped.paginate(10, params[:page])                      
end
```

**Comment by carlosramireziii** [comment]
@michaelkl I would agree with @j-dexx's recommendation of overriding the `index` method for this special use case. 

NOTE: In the current version, because the templates are rendered using local variables, setting an instance variable `@resources` will not work. 

[Here's the default `index` action code](https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L5). You'll want to copy that and adjust it to add an `unscoped` call in there. 

Hope that helps! If you have any further issue, feel free to re-open and post feedback.

**Comment by dev-cyprium** [comment]
How about using a bit of ruby **metaprogramming** to remove the scopes with reflection?
```
def index
  old_scopes = Publication.default_scopes
  Publication.default_scopes = []
  super
  Format.default_scopes = old_scopes
end
```
This sounds like a cleaner solution to me at this moment, and It's self contained and clean using some Ruby magic.
