### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by achernyak** [thoughtbot/administrate#652]
I just see a lot of open pull requests and issues without much being added in the past few month.

**Comment by jakesen** [comment]
I wonder the same thing. I have had no feedback on my PR (https://github.com/thoughtbot/administrate/pull/637) and a friend I recommended administrate to ended up going with active admin instead because there was no clear commitment to or official support for Rails 5.

**Comment by bgreg** [comment]
I think the main developer for this project has moved on, and there isn't a clear replacement yet.

**Comment by clemensg** [comment]
@graysonwright

**Comment by erickreutz** [comment]
What a bummer.

**Comment by jackjennings** [comment]
The developer no longer seems to work at Thoughtbot according to his website. Guess this project had a Bus Factor == 1. Can someone from Thoughtbot mark this as Deprecated please?

**Comment by tute** [comment]
Calling in @danbee and @JoelQ for context on this thread. Thank you!

**Comment by jaxn** [comment]
Just found Administrate this morning and was excited to see it was a Thoughtbot project.

Started setting it up for an app and immediately ran into issues. Came to see if the issue had been reported before and found this thread.

I am glad that I had trouble getting Administrate going and found this before I integrated it into my project.

If the project is deprecated, Thoughtbot should update Github as well as the [Thoughtbot announcement of the Administrate project](https://robots.thoughtbot.com/announcing-administrate)

**Comment by ZombieHarvester** [comment]
That would make you think twice before depending on Thoughtbot's libs, woudn't it? Hyped project has been abandoned months ago and Thoughtbot seems to be unaware.

**Comment by danbee** [comment]
Hi @jaxn, sorry you have had some trouble with Administrate. The project got neglected for a while after the original maintainer left thoughtbot, but we're working to bring it back up to scratch now. Please tell us about the issue you're having and I'll do my best to help you.

**Comment by jackjennings** [comment]
@danbee Rails 5 is a huge blocker at this point (given 5 has been released for months)—there's a PR with a valiant effort to get there that seems to be ignored now. Outside of the codebase: closing or just clearing out most of the issues and pull requests that have accumulated (many of which seem to be duplicates), and having a roadmap as to direction of the library would make it so that I could feel confident using this library in new projects.

I've already deployed Administrate in a couple of sites and I like a lot of the abstractions and interfaces that it provides—much more so than the alternative. I'd be happy to contribute time to getting to 1.0 if there's life left in this project.

**Comment by JoelQ** [comment]
This project has been through a bit of a hiatus. @danbee and I are picking this up.

@jackjennings thanks for your offer!

As far as Rails 5 goes, we can continue the discussion in #623 .

Since this issue has been answered (Yes, administrate is being maintained) I'm going to close this issue.
