### ISSUE TITLE
How do I display an image instead of the image_path?

### ISSUE THREAD

**Issue by marcamillion** [thoughtbot/administrate#655]
I have a `Profile` model, and on that model I have an `.avatar` field that is a path to the image.

In my Profile Administrate view, I don't want it to show the path to the image, I want it to display the image.

Per [this guide](http://administrate-prototype.herokuapp.com/adding_custom_field_types), I attempted to create a field called `avatar` and in the `app/views/fields/avatar_field/_show.html.erb`, I had this:

    <%= image_tag(field.avatar) %>

But that still doesn't work.

Thoughts?

**Comment by j-dexx** [comment]
What are you using to upload images?

**Comment by marcamillion** [comment]
I will be using carrierwave or something.

Either way, the URL referenced in Administrate's admin section is simply that...a URL. All Administrate needs to do is just put an image_tag around the URL, instead now it shows the actual URL.

**Comment by j-dexx** [comment]
So if you've followed the linked to guide all you need to do is put an image tag in `app/views/avatar_field/_show.html.erb`

I'm using carrierwave and i've just got `image_tag field.data` as the data is the attribute data from the record.

**Comment by JoelQ** [comment]
I aggre with @j-dexx's suggestion. You can see an example at https://administrate-prototype.herokuapp.com/customizing_attribute_partials

 Alternatively you could create your own custom avatar field instead of modifying Administrate's existing image field. That sounds like overkill in your situation but is an option if you need to do anything more complex. There is some documentation on that https://administrate-prototype.herokuapp.com/adding_custom_field_types
