### ISSUE TITLE
Previewing on the Cloud

### ISSUE THREAD

**Issue by OmarZV** [thoughtbot/administrate#674]
Hi guys,

Love your gem, the only thing is that I'm using Nitrous.io - it allows me to code on the cloud thus I don't use localhost:3000. Is there a way that I can customize this so I can use it in Nitrious.io . I get this error message on my app specifically screenshot below 
Thanks guys :)

**Comment by OmarZV** [comment]
![screen shot 2016-10-24 at 8 41 47 am](https://cloud.githubusercontent.com/assets/16312270/19646333/fd59b794-99c6-11e6-9bca-65f1275d82a7.png)

**Comment by JoelQ** [comment]
@OmarZV I believe your issue isn't related to being on Nitrous. Instead, it seems to be the same problem described in #615. You'll need to require `bourbon` so that the layout can find the stylesheet.

Since this seems to be a duplicate I'm going to close this issue but feel free to continue the conversation on #615
