### ISSUE TITLE
General question: What should the community expect in terms of commitment to merging PRs

### ISSUE THREAD

**Issue by dbryand** [thoughtbot/administrate#709]
At the recommendation of a trusted person familiar (obsessed?) with Thoughtbot, I moved a client away from ActiveAdmin and onto Administrate a while back. I should have done more due diligence, but it's been painful to solve problems that we simple in AA. Some of the issues that have hurt are addressed in some of the ~100 open pull requests in the queue.

Of course, I understand that this is free, open source software and I'm thankful for all of the great libraries that Thoughtbot has shared with the world. That said, it would be helpful if the maintainers of the project could chime in on what they see as the future of this project and whether or not there is a plan to address some of those open PRs.

Time and attention are scarce, so I totally understand if this is the pace that we should expect from this project. That is fine, I'd just like to know so I can make a more informed decision when selecting an admin library.

Thanks!

**Comment by dts** [comment]
I also appreciate what has been started with Administrate.  The thoughtful structure has been quite helpful to me.  Since the codebase is relatively straightforward, I have had no trouble building out the pieces that I need in order to succeed personally.  That being said, there are a lot of things that would be generally useful to add, either in separate gems (refile support, polymorphic fields, auto-completing belongs-to fields, etc), gists, or into the core of the application.

I don't want to tread on any toes, but there is such great momentum right now behind this gem that I don't want to let Administrate languish either.  My suggestion is to start with Pieter Hintjens's 10 rules (http://hintjens.com/blog:95), and quickly move past some of the simple hurdles that exist currently.  Promoting some active community members to being collaborators would do wonders to the PR and Issue queues.

**Comment by nickcharlton** [comment]
Thank you all for your comments. I saw this issue fly by on Twitter yesterday and thought I'd go and have a look. I wasn't quite expecting so many open issues and PRs. This is definitely something we still care about; I've certainly been encouraging us to use it on client projects, and so we've seen the same problems as you have.

This needs some dedicated time on it so that we can make a dent in the long list of issues and PRs. I'm going to do that over the next few days and see where we can get.

So far we've not done a great job of that. Long term, I think we should look at expanding the maintainers.

I'm going to close this for now, but feel free to open up another issue if things don't improve.

**Comment by dbryand** [comment]
Thanks for the input and plan. Cheers.
