### ISSUE TITLE
Unable to pass instance variables from the Controller to the View

### ISSUE THREAD

**Issue by icstunna** [thoughtbot/administrate#711]
In one of my views, specifically the `user show` page. I created a form that I use to take notes about specific users. Into that form I pass as parameters, the instance of a user as well a instance of a new Note. 

I've been forced to instantiate these classes on the view page. When I created the instances on the controller, the variables were not able to be passed into the View however, when I tried to debug and inspect these variables I've noticed the variables would still be recognized and printed on the server. 

I'm curious how it's possible to be able to inspect variables on a controller but not have it passed onto the view. 

The Controller in question:
```
module Admin
  class UsersController < Admin::ApplicationController
    def show
        super
        id = params[:id].to_i
        
        @user = User.find(id)
        @note = Note.new
    end
  end
end
```

The View and form:
```
<% @user = User.find(params[:id]) %>

<%= form_for Note.new, :url => {:action => "create", :user_id => @user.id, :controller => "notes"} do |f| %>
  <%= f.label :note %>
  <%= f.text_field :content %>
  
  <%= f.submit %>
<% end %>
```

**Comment by sbhargava** [comment]
Would love an answer to this issue as well!

**Comment by cjlee37** [comment]
+1

**Comment by kuboon** [comment]
I think administrate has another philosophy on view, not same as Rails way.
Each column on the target model builds the administrate view.
So if you want make ``user`` to have ``note``, you would add ``note`` method on ``User`` model by ``has_one`` or ``belongs_to``.
Then you would change ``app/dashboards/user_dashboard.rb`` like this:

```
ATTRIBUTE_TYPES = {
#...
  note: Field::BelongsTo,
#...
}

FORM_ATTRIBUTES = {
#...
  :note,
#...
}
```

**Comment by icstunna** [comment]
Thank you for that @kuboon. I think your solution is more inline with the ideals of Administrates architecture. 

I went ahead and created an association between Users and Notes. 

I stated that a User `has_many :notes`
```
class User < ActiveRecord::Base
  has_many :notes
end

```

While a Note `belongs_to :user`, and also `belongs_to :author` by way of the User table. This is to give credit to a specific user Author for a Note. 

```
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :author, class_name: :User, foreign_key: :author_id
end

class CreateNotes < ActiveRecord::Migration
  def change
    create_table :notes do |t|
      t.belongs_to :user, index: true
      t.belongs_to :author, index: true
      t.text :content
      t.timestamps null: false
    end
  end
end
```

This seems to work just fine when I'm creating a Note from the Dashboard however for some odd reason when I try to edit a User with a Note. It provides me with a ```undefined method `note_id' for #<User:0x007fdd1f340e00>``` error. 

This is despite following the guidelines of creating a `:note Field::BelongsTo` attribute type, and placing a `:note` key on the show and form pages attributes. 

I also tried a `:note Field::HasMany` attribute type since that seems more intuitive according the user model however I then receive a ```undefined method `limit' for nil:NilClass``` error. 

I appreciate any input and feedback.

**Comment by kuboon** [comment]
if you wrote like this:

```
class User < ActiveRecord::Base
  has_many :notes
end
```
make sure ```app/dashboards/user_dashboard.rb``` would be:

```
ATTRIBUTE_TYPES = {
#...
  notes: Field::HasMany,
#...
}
```

**Comment by carlosramireziii** [comment]
@icstunna The commenters above are correct-- Administrate does not use instance variables to pass data to its views; instead, it uses local variables. [See here for example](https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L12)

As far as getting the form to work, it would be best to add the fields like @kuboon suggested above. If not, you can always add the data you need yourself by overriding the controller (but remember to use local variables instead of instance variables). 

Hope that helps!

**Comment by dduqueti** [comment]
@carlosramireziii Hello! This is something I'm also trying without luck.

I'm trying to pass a `count` to be displayed in the dashboard outside of the collection. It's a global variable that will depend on a query being made in the controller.

I've tried several things without luck, overriding the controller and copy pasting the `index` code on https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L12 ends up being an error because we need to include `apply_collection_includes` and later on `dashboard.collection_includes` fails.

Could you give me a light on the correct approach for this?
