### ISSUE TITLE
Format for datetimepickers should be customizable

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#716]
Right now the format for all datetimepickers is hardcoded to include time elements:

``` javascript
$(function () {
  $(".datetimepicker").datetimepicker({
    debug: false,
    format: "YYYY-MM-DD HH:mm:ss",
  });
});
```

However, if you want to create a date field, then having a format that includes time elements doesn't make any sense.

Here is what I have in my app:

``` javascript
(function () {
  $("[data-datetimepicker]").each(function (i, el) {
    var field = $(el);
    var format = field.data("format") || "YYYY-MM-DD HH:mm:ss";

    field.datetimepicker({
      debug: false,
      format: field.data("format"),
    });
  });
})();
```

This would, of course, necessitate changing the views to use `data` attributes instead of a class.

**Comment by carlosramireziii** [comment]
Would #757 help here?

**Comment by mcmire** [comment]
Yup, that would work just as well. 👍

**Comment by pablobm** [comment]
Two things here:

1. Picker should differentiate between date and date+time.
2. Format should be customisable.

The first is now fixed. Since https://github.com/thoughtbot/administrate/pull/903, the current `DateTime` and `Time` fields render with data attributes that work as a hint for the JS widget.

The second is not yet possible. My first idea would be to add a new option to both fields, `format` (or similar), which then will be used for a new data attribute that the JS will pick up and use for its own `format` option. Ideally there should be some sort of locale integration too, but I think this can come later.

This second one is a potential easy contribution, if someone wants to give it a go. Still, for now I'm going to close this as it's been a while. Feel free to keep commenting if you have more input.
