### ISSUE TITLE
Admin model in rails app

### ISSUE THREAD

**Issue by evheny0** [thoughtbot/administrate#855]
# Feature suggestion
If you have `Admin` model in your project it can be really annoying that `administrate` have `Admin` as a module too. So it could be a nice improvement if during running a `rails generate administrate:install` generator will stop and tell you that you have a `Admin` model, which will intersect with `Admin` module  in gem.

**Comment by nickcharlton** [comment]
This sounds like a good idea! I especially like catching it only if you've got an admin model already.

I've seen there be an `Admin` model in enough Rails projects myself to be confident in thinking this is something people see often.

Would you be up for contributing a PR for this?

**Comment by munza** [comment]
Hello @evheny0 and @nickcharlton,
I have created a pull request #917 to solve this issue by adding `--module` option in the generators commands to use a specific module name instead of the default `Admin` namespacing.
Currently, it is failing the tests, but I will cover that in a few days. In the mean time can you please share your feedback on the PR.
Thanks.

**Comment by nickcharlton** [comment]
I'm going to close this as this should be solved [through namespacing](https://administrate-demo.herokuapp.com/getting_started). Please open a new issue if this isn't the case!
